// Analysis view — grades each rookie pick on Year-1 fantasy impact based on
// the drafting team's incumbent depth chart and the round of selection.
// Data comes from analysis.js, generated by scripts/build-analysis.mjs.

const GRADE_ORDER = ['A+', 'A', 'B', 'C', 'D'];
const GRADE_COLOR = {
  'A+': { bg: 'oklch(60% 0.16 145)', fg: '#fff' },
  'A':  { bg: 'oklch(58% 0.13 145)', fg: '#fff' },
  'B':  { bg: 'oklch(64% 0.12 90)',  fg: '#1a1a17' },
  'C':  { bg: 'oklch(68% 0.13 55)',  fg: '#1a1a17' },
  'D':  { bg: 'oklch(56% 0.14 25)',  fg: '#fff' },
};
const STATUS_LABEL = { open: 'Open', contested: 'Contested', locked: 'Locked' };
const STATUS_COLOR = {
  open:      { bg: 'oklch(92% 0.06 145)', fg: 'oklch(35% 0.12 145)' },
  contested: { bg: 'oklch(92% 0.07 70)',  fg: 'oklch(35% 0.12 55)'  },
  locked:    { bg: 'oklch(92% 0.05 25)',  fg: 'oklch(40% 0.13 25)'  },
};

const POSITIONS = ['QB', 'RB', 'WR', 'TE'];

const AnalysisView = ({ search, palette, dark, density, hoverPick, setHoverPick }) => {
  const data = window.ANALYSIS_DATA;
  const teams = window.DRAFT_DATA.teams;
  const [posFilter, setPosFilter] = React.useState('all');
  const [gradeFilter, setGradeFilter] = React.useState('all');
  const [sortBy, setSortBy] = React.useState('score'); // 'score' | 'pick'

  if (!data) {
    return (
      <div className="analysis-empty">
        <div className="team-empty-icon">—</div>
        <div className="team-empty-text">Analysis data not loaded.</div>
        <div className="team-empty-sub">run scripts/build-analysis.mjs</div>
      </div>
    );
  }

  const q = (search || '').trim().toLowerCase();
  const rows = data.picks
    .filter(p => !q || p.name.toLowerCase().includes(q))
    .filter(p => posFilter === 'all' || p.pos === posFilter)
    .filter(p => gradeFilter === 'all' || p.grade === gradeFilter)
    .sort((a, b) => sortBy === 'score' ? b.score - a.score : a.overall - b.overall);

  const counts = GRADE_ORDER.reduce((m, g) => {
    m[g] = data.picks.filter(p => p.grade === g).length;
    return m;
  }, {});

  return (
    <div className="analysis-view">
      <div className="analysis-meta">
        <div>
          <span className="analysis-meta-label">Source</span>
          <span className="analysis-meta-value">{data.source}</span>
        </div>
        <div>
          <span className="analysis-meta-label">Season</span>
          <span className="analysis-meta-value">{data.season}</span>
        </div>
        <div>
          <span className="analysis-meta-label">Generated</span>
          <span className="analysis-meta-value">{data.generatedAt}</span>
        </div>
      </div>

      <div className="analysis-controls">
        <div className="analysis-grade-bar">
          <button
            type="button"
            className={`grade-pill all${gradeFilter === 'all' ? ' is-active' : ''}`}
            onClick={() => setGradeFilter('all')}
          >
            All <span className="grade-pill-count">{data.picks.length}</span>
          </button>
          {GRADE_ORDER.map(g => {
            const c = GRADE_COLOR[g];
            const active = gradeFilter === g;
            return (
              <button
                key={g}
                type="button"
                className={`grade-pill${active ? ' is-active' : ''}`}
                onClick={() => setGradeFilter(active ? 'all' : g)}
                style={{ background: c.bg, color: c.fg }}
              >
                {g} <span className="grade-pill-count">{counts[g] || 0}</span>
              </button>
            );
          })}
        </div>

        <div className="analysis-filters">
          <div className="analysis-pos-filter">
            <button
              type="button"
              className={`pos-chip${posFilter === 'all' ? ' is-active' : ''}`}
              onClick={() => setPosFilter('all')}
            >All</button>
            {POSITIONS.map(p => (
              <button
                key={p}
                type="button"
                data-pos={p}
                className={`pos-chip${posFilter === p ? ' is-active' : ''}`}
                onClick={() => setPosFilter(posFilter === p ? 'all' : p)}
              >{p}</button>
            ))}
          </div>
          <div className="analysis-sort">
            <span className="round-filter-label">Sort</span>
            <button
              type="button"
              className={`round-pill${sortBy === 'score' ? ' is-active' : ''}`}
              onClick={() => setSortBy('score')}
            >Grade</button>
            <button
              type="button"
              className={`round-pill${sortBy === 'pick' ? ' is-active' : ''}`}
              onClick={() => setSortBy('pick')}
            >Pick</button>
          </div>
        </div>
      </div>

      <div className="analysis-list">
        {rows.length === 0 && (
          <div className="empty-row">No picks match your filters.</div>
        )}
        {rows.map(p => {
          const team = teams[p.team] || teams[p.team === 'NEP' ? 'NE' : p.team];
          const swatch = window.roundSwatch(palette, p.round, dark);
          const gc = GRADE_COLOR[p.grade] || GRADE_COLOR.C;
          const sc = STATUS_COLOR[p.roomStatus] || STATUS_COLOR.open;
          const isHover = hoverPick === p.key;
          return (
            <div
              key={p.key}
              className={`analysis-row${isHover ? ' is-hover' : ''}`}
              onMouseEnter={() => setHoverPick(p.key)}
              onMouseLeave={() => setHoverPick(null)}
            >
              <div className="analysis-grade" style={{ background: gc.bg, color: gc.fg }}>
                {p.grade}
              </div>
              <div className="analysis-pick" style={{ background: swatch.bg, color: swatch.fg }}>
                <span className="rd">RD {p.round}</span>
                <span className="ov">{p.overall}</span>
              </div>
              <div className="analysis-pos" data-pos={p.pos}>{p.pos}</div>
              <div className="analysis-info">
                <div className="analysis-name">{p.name}</div>
                <div className="analysis-school">{p.school}</div>
              </div>
              <div className="analysis-team">
                <TeamBadge code={p.team} size={32} />
              </div>
              <div className="analysis-room">
                <span
                  className="analysis-room-status"
                  style={{ background: sc.bg, color: sc.fg }}
                >{STATUS_LABEL[p.roomStatus]}</span>
                {p.starter && (
                  <span className="analysis-room-starter">vs {p.starter}</span>
                )}
              </div>
              <div className="analysis-rationale">{p.rationale}</div>
            </div>
          );
        })}
      </div>

      <div className="analysis-legend">
        <div className="analysis-legend-title">How grades are calculated</div>
        <div className="analysis-legend-body">
          <code>score = draft_capital × room_factor</code> &nbsp;·&nbsp;
          A+ ≥ 0.85, A ≥ 0.70, B ≥ 0.55, C ≥ 0.40, D &lt; 0.40 &nbsp;·&nbsp;
          rooms bucketed from {data.season} EPA, target share, and carries/game
        </div>
      </div>
    </div>
  );
};

window.AnalysisView = AnalysisView;
