// Analysis view — live depth-chart juxtaposition.
// On mount we fetch each NFL team's CURRENT roster directly from ESPN's
// public site API, join skill players against the static stats lookup
// (window.STATS, generated by scripts/build-analysis.mjs from nflverse),
// and compute room status client-side. Rosters are always live; stats
// can refresh on a separate cadence.

const { useEffect, useMemo, useState } = React;

// Rookie role — what we think the rookie's Year-1 path looks like.
// Derived from round (draft capital) and the team's room state. R1 picks
// override the room: teams don't draft a 1st-rounder to bench him.
const ROLE_LABEL = {
  starter:       'Likely starter',
  developmental: 'Developmental',
  competing:     'Competing for snaps',
  backup:        'Backup / dev',
};
const ROLE_COLOR = {
  starter:       { bg: 'oklch(92% 0.06 145)', fg: 'oklch(35% 0.12 145)' },
  developmental: { bg: 'oklch(92% 0.06 280)', fg: 'oklch(35% 0.12 280)' },
  competing:     { bg: 'oklch(92% 0.07 70)',  fg: 'oklch(35% 0.12 55)'  },
  backup:        { bg: 'oklch(92% 0.05 25)',  fg: 'oklch(40% 0.13 25)'  },
};
const ROLE_COLOR_DARK = {
  starter:       { bg: 'oklch(28% 0.07 145)', fg: 'oklch(82% 0.10 145)' },
  developmental: { bg: 'oklch(28% 0.07 280)', fg: 'oklch(82% 0.10 280)' },
  competing:     { bg: 'oklch(28% 0.07 60)',  fg: 'oklch(82% 0.10 65)'  },
  backup:        { bg: 'oklch(28% 0.07 25)',  fg: 'oklch(82% 0.10 25)'  },
};

// Round × room state → expected role.
//   isElite = the incumbent isn't just employed, they're top-tier in stats.
//   That blocks even R1/R2 rookies (Stafford-vs-Ty-Simpson case).
function roleFor(round, roomStatus, isElite) {
  if (round <= 1) return isElite ? 'developmental' : 'starter';
  if (round === 2) {
    if (isElite) return 'developmental';
    return roomStatus === 'locked' ? 'competing' : 'starter';
  }
  if (round === 3) {
    if (isElite) return 'backup';
    return roomStatus === 'open' ? 'starter' : 'competing';
  }
  // R4–R7
  return roomStatus === 'open' && !isElite ? 'competing' : 'backup';
}

const ANALYSIS_POSITIONS = ['QB', 'RB', 'WR', 'TE'];

const THRESHOLDS = {
  // QB — passer rating is the ESPN-available proxy for EPA/dropback.
  // ~95 rating ≈ above-average starter; 300+ attempts implies full-time.
  QB_LOCKED_RATING: 95,
  QB_LOCKED_MIN_ATTEMPTS: 300,
  QB_CONTESTED_MIN_ATTEMPTS: 100,
  // Elite = depth-chart starter who's also putting up top-tier numbers,
  // not just employed. Blocks even R1/R2 rookies in their first season
  // (Stafford, Mahomes, Goff caliber).
  QB_ELITE_MIN_ATTEMPTS: 400,
  QB_ELITE_MIN_RATING: 95,
  RB_LOCKED_CARRIES_PER_GAME: 14,
  RB_LOCKED_CARRY_SHARE: 0.65,
  RB_CONTESTED_CARRIES_PER_GAME: 6,
  RB_CONTESTED_CARRY_SHARE: 0.40,
  RB_ELITE_MIN_CARRIES: 250,
  RB_ELITE_MIN_SHARE: 0.65,
  WR_LOCKED_TARGET_SHARE: 0.22,
  WR_CONTESTED_TARGET_SHARE: 0.12,
  // Elite WRs are filtered by yards-per-game, not target share. A bad
  // offense's slot WR (Wan'Dale Robinson at 40% share) clears most
  // share-based gates; AJ Brown on a balanced offense (31% share) doesn't.
  // Yards captures both volume AND efficiency so the alpha receivers
  // surface even when targets are spread across multiple weapons.
  WR_ELITE_MIN_YPG: 70,
  WR_ELITE_MIN_GAMES: 6,
  TE_LOCKED_TARGET_SHARE: 0.15,
  TE_LOCKED_MIN_TARGETS: 80,
  TE_CONTESTED_MIN_TARGETS: 40,
  TE_ELITE_MIN_YPG: 50,
  TE_ELITE_MIN_GAMES: 6,
};

const fmt = (n, d = 3) => Number(n).toFixed(d).replace(/\.?0+$/, '');

// ── Bucketers (mirror scripts/build-analysis.mjs) ───────────────────────────
// Order players by depth-chart rank first, then by stats volume for anyone
// not on the chart. Returns the array used for both the incumbents display
// and the bucketing decision.
function orderForRoom(players, dcIds, statKey) {
  const byId = Object.fromEntries(players.map(p => [p.espn_id, p]));
  const ordered = [];
  const seen = new Set();
  for (const id of dcIds) {
    if (byId[id]) { ordered.push(byId[id]); seen.add(id); }
  }
  const rest = players.filter(p => !seen.has(p.espn_id))
    .sort((a, b) => (b[statKey] || 0) - (a[statKey] || 0));
  ordered.push(...rest);
  return ordered;
}

function bucketQB(qbs, dcIds) {
  const ordered = orderForRoom(qbs, dcIds, 'attempts');
  const incumbents = ordered.slice(0, 3).map(p => ({
    name: p.name,
    primary_label: 'Rtg',
    primary_value: fmt(p.passer_rating || 0, 1),
    secondary_label: 'att',
    secondary_value: String(p.attempts || 0),
  }));
  if (!ordered.length) return { status: 'open', starter: null, isElite: false, incumbents: [] };

  // Locked if the team has named a QB1 on the depth chart, OR if any player
  // had dominant volume last season (high attempts ≈ entrenched starter).
  const hasDcStarter = dcIds.length > 0 && qbs.some(p => p.espn_id === dcIds[0]);
  const topByVolume = ordered[0] && (ordered[0].attempts || 0) >= THRESHOLDS.QB_LOCKED_MIN_ATTEMPTS;
  const top = ordered[0];

  let status;
  if (hasDcStarter || topByVolume) status = 'locked';
  else if ((top.attempts || 0) >= THRESHOLDS.QB_CONTESTED_MIN_ATTEMPTS) status = 'contested';
  else status = 'open';

  // Elite = depth-chart starter who's also top-tier statistically. Blocks
  // even R1 rookies in their first season.
  const dcStarter = hasDcStarter ? qbs.find(p => p.espn_id === dcIds[0]) : top;
  const isElite = !!dcStarter
    && (dcStarter.attempts || 0)      >= THRESHOLDS.QB_ELITE_MIN_ATTEMPTS
    && (dcStarter.passer_rating || 0) >= THRESHOLDS.QB_ELITE_MIN_RATING;

  return { status, starter: top.name, isElite, incumbents };
}

function bucketRB(rbs, dcIds) {
  if (!rbs.length) return { status: 'open', starter: null, isElite: false, incumbents: [] };
  const teamCarries = rbs.reduce((s, p) => s + (p.carries || 0), 0);
  const ordered = orderForRoom(rbs, dcIds, 'carries');
  const incumbents = ordered.slice(0, 3).map(p => {
    const games = p.games || 17;
    const cpg = (p.carries || 0) / games;
    const share = teamCarries ? (p.carries || 0) / teamCarries : 0;
    return {
      name: p.name,
      primary_label: 'car/g',
      primary_value: fmt(cpg, 1),
      secondary_label: 'share',
      secondary_value: `${Math.round(share * 100)}%`,
    };
  });
  const top = ordered[0];
  if (!top) return { status: 'open', starter: null, isElite: false, incumbents };

  const hasDcStarter = dcIds.length > 0 && rbs.some(p => p.espn_id === dcIds[0]);
  const games = top.games || 17;
  const cpg = (top.carries || 0) / games;
  const carryShare = teamCarries ? (top.carries || 0) / teamCarries : 0;
  const topByVolume = cpg >= THRESHOLDS.RB_LOCKED_CARRIES_PER_GAME
                   && carryShare >= THRESHOLDS.RB_LOCKED_CARRY_SHARE;

  let status;
  if (hasDcStarter || topByVolume) status = 'locked';
  else if (cpg >= THRESHOLDS.RB_CONTESTED_CARRIES_PER_GAME ||
           carryShare >= THRESHOLDS.RB_CONTESTED_CARRY_SHARE) status = 'contested';
  else status = 'open';

  // Elite = bell-cow incumbent (Bijan, Henry, Saquon caliber).
  const dcStarter = hasDcStarter ? rbs.find(p => p.espn_id === dcIds[0]) : top;
  const dcCarries = dcStarter?.carries || 0;
  const dcShare = teamCarries ? dcCarries / teamCarries : 0;
  const isElite = !!dcStarter
    && dcCarries >= THRESHOLDS.RB_ELITE_MIN_CARRIES
    && dcShare   >= THRESHOLDS.RB_ELITE_MIN_SHARE;

  return { status, starter: top.name, isElite, incumbents };
}

// Target share is computed dynamically from the players passed in (which are
// the team's current pass-catchers from ESPN's roster). teamPositionTargets
// is the denominator: total targets at THIS POSITION on the team, not all
// pass-catchers combined — we want WR1's share of the WR target pie.
function bucketWR(wrs, dcIds) {
  const teamTargets = wrs.reduce((s, p) => s + (p.targets || 0), 0);
  const ordered = orderForRoom(wrs, dcIds, 'targets');
  const incumbents = ordered.slice(0, 3).map(p => {
    const share = teamTargets ? (p.targets || 0) / teamTargets : 0;
    return {
      name: p.name,
      primary_label: 'tgt%',
      primary_value: `${Math.round(share * 100)}%`,
      secondary_label: 'targets',
      secondary_value: String(p.targets || 0),
    };
  });
  const top = ordered[0];
  if (!top) return { status: 'open', starter: null, isElite: false, incumbents: [] };

  const hasDcStarter = dcIds.length > 0 && wrs.some(p => p.espn_id === dcIds[0]);
  const ts = teamTargets ? (top.targets || 0) / teamTargets : 0;
  const topByVolume = ts >= THRESHOLDS.WR_LOCKED_TARGET_SHARE;

  let status;
  if (hasDcStarter || topByVolume) status = 'locked';
  else if (ts >= THRESHOLDS.WR_CONTESTED_TARGET_SHARE) status = 'contested';
  else status = 'open';

  // Elite = true alpha WR1 (CeeDee, JJ, Chase, AJ Brown caliber).
  // Receiving yards per game catches them even when target share is split.
  const dcStarter = hasDcStarter ? wrs.find(p => p.espn_id === dcIds[0]) : top;
  const dcGames = dcStarter?.games || 0;
  const dcYpg = dcGames ? (dcStarter.receiving_yards || 0) / dcGames : 0;
  const isElite = !!dcStarter
    && dcGames >= THRESHOLDS.WR_ELITE_MIN_GAMES
    && dcYpg   >= THRESHOLDS.WR_ELITE_MIN_YPG;

  return { status, starter: top.name, isElite, incumbents };
}

function bucketTE(tes, dcIds) {
  const teamTargets = tes.reduce((s, p) => s + (p.targets || 0), 0);
  const ordered = orderForRoom(tes, dcIds, 'targets');
  const incumbents = ordered.slice(0, 2).map(p => {
    const share = teamTargets ? (p.targets || 0) / teamTargets : 0;
    return {
      name: p.name,
      primary_label: 'tgt%',
      primary_value: `${Math.round(share * 100)}%`,
      secondary_label: 'targets',
      secondary_value: String(p.targets || 0),
    };
  });
  const top = ordered[0];
  if (!top) return { status: 'open', starter: null, isElite: false, incumbents: [] };

  const hasDcStarter = dcIds.length > 0 && tes.some(p => p.espn_id === dcIds[0]);
  const ts = teamTargets ? (top.targets || 0) / teamTargets : 0;
  const t = top.targets || 0;
  const topByVolume = ts >= THRESHOLDS.TE_LOCKED_TARGET_SHARE
                   && t  >= THRESHOLDS.TE_LOCKED_MIN_TARGETS;

  let status;
  if (hasDcStarter || topByVolume) status = 'locked';
  else if (t >= THRESHOLDS.TE_CONTESTED_MIN_TARGETS) status = 'contested';
  else status = 'open';

  // Elite = LaPorta / Kittle / Bowers caliber (true TE1, not just employed).
  const dcStarter = hasDcStarter ? tes.find(p => p.espn_id === dcIds[0]) : top;
  const dcGames = dcStarter?.games || 0;
  const dcYpg = dcGames ? (dcStarter.receiving_yards || 0) / dcGames : 0;
  const isElite = !!dcStarter
    && dcGames >= THRESHOLDS.TE_ELITE_MIN_GAMES
    && dcYpg   >= THRESHOLDS.TE_ELITE_MIN_YPG;

  return { status, starter: top.name, isElite, incumbents };
}

const BUCKETER = { QB: bucketQB, RB: bucketRB, WR: bucketWR, TE: bucketTE };

// ── ESPN fetch ──────────────────────────────────────────────────────────────
const ESPN_ROSTER = (slug) =>
  `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${slug}/roster`;
const ESPN_DEPTHCHART = (slug) =>
  `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${slug}/depthchart`;

async function fetchTeamRoster(slug) {
  const r = await fetch(ESPN_ROSTER(slug));
  if (!r.ok) throw new Error(`${slug} → ${r.status}`);
  const json = await r.json();
  return (json.athletes || [])
    .flatMap(g => g.items || [])
    .filter(p => ['QB','RB','WR','TE'].includes(p?.position?.abbreviation))
    .map(p => ({
      espn_id: String(p.id),
      name: p.fullName,
      position: p.position.abbreviation,
      age: p.age ? Number(p.age) : null,
    }));
}

// Returns { QB: [espn_id_in_rank_order], RB: [...], WR: [...], TE: [...] }.
// Walks the response defensively — ESPN's depth-chart shape varies between
// teams and we'd rather degrade gracefully than throw on an unfamiliar key.
async function fetchTeamDepthChart(slug, dumpFirst) {
  let json = null;
  try {
    const r = await fetch(ESPN_DEPTHCHART(slug));
    if (!r.ok) return null;
    json = await r.json();
  } catch {
    return null;
  }
  if (dumpFirst && json) {
    console.log(`[depthchart sample ${slug}]`, json);
  }

  const out = { QB: [], RB: [], WR: [], TE: [] };

  // Strategy: find every nested `athletes` array under a positionally-named
  // parent and bucket its items by ESPN's position.abbreviation. Handles
  // multiple known shapes (items[].positions{}, items[]{positions:[]}, etc.)
  const visit = (node) => {
    if (!node || typeof node !== 'object') return;
    if (Array.isArray(node)) { node.forEach(visit); return; }
    if (Array.isArray(node.athletes)) {
      const posAbbr =
        node?.position?.abbreviation ||
        node?.position?.parent?.abbreviation ||
        node?.abbreviation ||
        node?.name;
      const grp = (posAbbr || '').toString().toUpperCase().replace(/\d+$/, '');
      if (['QB','RB','WR','TE'].includes(grp)) {
        const sorted = [...node.athletes].sort(
          (a, b) => (Number(a.rank) || 99) - (Number(b.rank) || 99)
        );
        for (const a of sorted) {
          const id = String(a?.athlete?.id || a?.id || '');
          if (id && !out[grp].includes(id)) out[grp].push(id);
        }
      }
    }
    for (const k of Object.keys(node)) visit(node[k]);
  };
  visit(json);
  return out;
}

// Build a room by combining the live roster, the depth chart, and the static
// stats lookup. Depth chart wins on ordering (it's the team's official
// answer); stats are still used for the secondary "is anyone dominant?"
// signal and for the per-incumbent display.
//
// rookieNames is a Set of lowercased 2026 rookie names — we strip them from
// the roster so the rookie being analyzed doesn't appear as their own
// competition (and so other 2026 rookies don't either, since they haven't
// played as pros yet and would clutter the depth chart with zero-stat rows).
function buildRoom(roster, depthChart, position, statsLookup, rookieNames) {
  const players = roster
    .filter(p => p.position === position)
    .filter(p => !rookieNames.has((p.name || '').trim().toLowerCase()))
    .map(p => {
      const s = statsLookup[p.espn_id];
      return { ...(s || { games: 0 }), espn_id: p.espn_id, name: p.name, position };
    });
  const dcIds = depthChart?.[position] || [];
  return BUCKETER[position](players, dcIds);
}

// ── Component ──────────────────────────────────────────────────────────────
const AnalysisView = ({ search, palette, dark, hoverPick, setHoverPick }) => {
  const stats = window.STATS;
  const teams = window.DRAFT_DATA.teams;
  const [posFilter, setPosFilter] = useState('all');
  // teamData: { TEAM_CODE: { roster: [...], depthChart: { QB:[ids], RB:[], WR:[], TE:[] } } }
  const [teamData, setTeamData] = useState(null);
  const [error, setError] = useState(null);
  const [loadedAt, setLoadedAt] = useState(null);

  // Fetch live rosters AND depth charts in parallel.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const codes = Object.keys(teams).filter(c => c !== 'NEP');
      try {
        let dumped = false;
        const results = await Promise.all(codes.map(async code => {
          const slug = teams[code].espn;
          const [roster, depthChart] = await Promise.all([
            fetchTeamRoster(slug),
            fetchTeamDepthChart(slug, !dumped),
          ]);
          if (!dumped && depthChart) dumped = true;
          return [code, { roster, depthChart: depthChart || { QB: [], RB: [], WR: [], TE: [] } }];
        }));
        if (cancelled) return;
        setTeamData(Object.fromEntries(results));
        setLoadedAt(new Date());
      } catch (e) {
        if (!cancelled) setError(e.message);
      }
    })();
    return () => { cancelled = true; };
  }, [teams]);

  // 2026 rookie names — used to strip them out of every team's depth chart so
  // a rookie never appears as their own competition.
  const rookieNames = useMemo(
    () => new Set(window.DRAFT_DATA.picks.map(p => (p.name || '').trim().toLowerCase())),
    []
  );

  const rooms = useMemo(() => {
    if (!teamData || !stats) return null;
    const out = {};
    for (const code of Object.keys(teamData)) {
      out[code] = {};
      for (const pos of ANALYSIS_POSITIONS) {
        out[code][pos] = buildRoom(
          teamData[code].roster,
          teamData[code].depthChart,
          pos,
          stats.byEspnId,
          rookieNames
        );
      }
    }
    return out;
  }, [teamData, stats, rookieNames]);

  if (!stats) {
    return (
      <div className="analysis-empty">
        <div className="team-empty-icon">—</div>
        <div className="team-empty-text">Stats lookup not loaded.</div>
        <div className="team-empty-sub">run scripts/build-analysis.mjs</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="analysis-empty">
        <div className="team-empty-icon">!</div>
        <div className="team-empty-text">Could not reach ESPN to load live rosters.</div>
        <div className="team-empty-sub" style={{ marginTop: 8 }}>{error}</div>
        <div className="team-empty-sub" style={{ marginTop: 14, opacity: 0.7 }}>
          ESPN's public roster API may be blocked by your network or a browser extension.
        </div>
      </div>
    );
  }

  if (!rooms) {
    return (
      <div className="analysis-empty">
        <div className="team-empty-text">Loading rosters and depth charts from ESPN…</div>
        <div className="team-empty-sub" style={{ marginTop: 8 }}>32 teams in flight</div>
      </div>
    );
  }

  const picks = window.DRAFT_DATA.picks;
  const q = (search || '').trim().toLowerCase();
  const rows = picks
    .filter(p => !q || p.name.toLowerCase().includes(q))
    .filter(p => posFilter === 'all' || p.pos === posFilter)
    .sort((a, b) => a.overall - b.overall);

  const roleColor = (role) =>
    (dark ? ROLE_COLOR_DARK : ROLE_COLOR)[role] || ROLE_COLOR.competing;

  return (
    <div className="analysis-view">
      <div className="analysis-meta">
        <div>
          <span className="analysis-meta-label">Rosters</span>
          <span className="analysis-meta-value">ESPN, live</span>
        </div>
        <div>
          <span className="analysis-meta-label">Stats</span>
          <span className="analysis-meta-value">ESPN {stats.statsSeason}</span>
        </div>
        <div>
          <span className="analysis-meta-label">Loaded</span>
          <span className="analysis-meta-value">{loadedAt ? loadedAt.toLocaleTimeString() : '—'}</span>
        </div>
      </div>

      <div className="analysis-filters">
        <div className="analysis-pos-filter">
          <button
            type="button"
            className={`pos-chip${posFilter === 'all' ? ' is-active' : ''}`}
            onClick={() => setPosFilter('all')}
          >All</button>
          {ANALYSIS_POSITIONS.map(p => (
            <button
              key={p}
              type="button"
              data-pos={p}
              className={`pos-chip${posFilter === p ? ' is-active' : ''}`}
              onClick={() => setPosFilter(posFilter === p ? 'all' : p)}
            >{p}</button>
          ))}
        </div>
        <div className="analysis-count">
          {rows.length} / {picks.length} picks
        </div>
      </div>

      <div className="analysis-list">
        {rows.length === 0 && (
          <div className="empty-row">No picks match your filters.</div>
        )}
        {rows.map(p => {
          const teamCode = p.team === 'NEP' ? 'NE' : p.team;
          const team = teams[teamCode];
          const room = rooms[teamCode]?.[p.pos] || { status: 'open', incumbents: [] };
          const role = roleFor(p.round, room.status, room.isElite);
          const swatch = window.roundSwatch(palette, p.round, dark);
          const rc = roleColor(role);
          const key = `${p.pick}-${p.name}-${p.team}`;
          const isHover = hoverPick === key;
          const incumbents = room.incumbents || [];
          return (
            <div
              key={key}
              className={`dc-row${isHover ? ' is-hover' : ''}`}
              onMouseEnter={() => setHoverPick(key)}
              onMouseLeave={() => setHoverPick(null)}
            >
              <div className="dc-rookie">
                <div className="dc-pick" style={{ background: swatch.bg, color: swatch.fg }}>
                  <span className="rd">RD {p.round}</span>
                  <span className="ov">{p.overall}</span>
                </div>
                <div className="dc-pos" data-pos={p.pos}>{p.pos}</div>
                <div className="dc-rookie-info">
                  <div className="dc-rookie-name">{p.name}</div>
                  {p.school && <div className="dc-rookie-school">{p.school}</div>}
                </div>
              </div>

              <div className="dc-arrow" aria-hidden="true">→</div>

              <div className="dc-room">
                <div className="dc-room-header">
                  <TeamBadge code={p.team} size={28} />
                  <div className="dc-room-title">
                    <span className="dc-room-team">{team?.short}</span>
                    <span className="dc-room-pos">{p.pos} room</span>
                  </div>
                  <span
                    className="dc-status"
                    style={{ background: rc.bg, color: rc.fg }}
                    title={`${p.pos} room is ${room.status}`}
                  >{ROLE_LABEL[role]}</span>
                </div>
                {incumbents.length > 0 ? (
                  <ol className="dc-incumbents">
                    {incumbents.map((inc, i) => (
                      <li key={inc.name} className="dc-incumbent">
                        <span className="dc-incumbent-rank">{i + 1}</span>
                        <span className="dc-incumbent-name">{inc.name}</span>
                        <span className="dc-incumbent-stat">
                          <span className="dc-stat-value">{inc.primary_value}</span>
                          <span className="dc-stat-label">{inc.primary_label}</span>
                        </span>
                        <span className="dc-incumbent-stat secondary">
                          <span className="dc-stat-value">{inc.secondary_value}</span>
                          <span className="dc-stat-label">{inc.secondary_label}</span>
                        </span>
                      </li>
                    ))}
                  </ol>
                ) : (
                  <div className="dc-empty">No incumbents with meaningful {stats.statsSeason} production.</div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="analysis-legend">
        <div className="analysis-legend-title">How role is determined</div>
        <div className="analysis-legend-body">
          The badge reflects the rookie's expected Year-1 path, combining round
          with the incumbent's depth-chart standing and stats.
          {' '}<strong>R1</strong> picks are <strong>Likely starter</strong> — unless the
          incumbent is statistically elite (top-tier volume + efficiency), in which case
          the rookie sits as <strong>Developmental</strong> (Ty Simpson behind Stafford,
          Jordan Love behind Rodgers).
          {' '}<strong>R2</strong> mirrors R1 but drops to <strong>Competing</strong> in
          locked-by-name rooms (entrenched but not elite).
          {' '}<strong>R3</strong> needs an open room to start; otherwise competing,
          and backup behind elite incumbents.
          {' '}<strong>R4-R7</strong> need an open room just to compete; everything
          else is backup.
          {' '}"Elite" thresholds: QB ≥400 att with ≥95 rating; RB ≥250 carries with
          ≥65% share; WR ≥70 receiving yds/game; TE ≥50 receiving yds/game.
          {' '}Rosters + depth charts live from ESPN; stats from ESPN season{' '}
          <strong>{stats.statsSeason}</strong>.
        </div>
      </div>
    </div>
  );
};

window.AnalysisView = AnalysisView;
