// Auto-generated by scripts/build-analysis.mjs — do not edit by hand.
window.ANALYSIS_DATA = {
  "generatedAt": "2026-04-26",
  "season": 2024,
  "source": "nflverse stats_player_reg",
  "thresholds": {
    "QB_LOCKED_EPA_PER_DB": 0.05,
    "QB_LOCKED_MIN_DROPBACKS": 300,
    "QB_CONTESTED_MIN_DROPBACKS": 100,
    "RB_LOCKED_CARRIES_PER_GAME": 14,
    "RB_LOCKED_CARRY_SHARE": 0.65,
    "RB_CONTESTED_CARRIES_PER_GAME": 6,
    "RB_CONTESTED_CARRY_SHARE": 0.4,
    "WR_LOCKED_TARGET_SHARE": 0.22,
    "WR_CONTESTED_TARGET_SHARE": 0.12,
    "TE_LOCKED_TARGET_SHARE": 0.15,
    "TE_LOCKED_MIN_TARGETS": 80,
    "TE_CONTESTED_MIN_TARGETS": 40
  },
  "rooms": {
    "ARI": {
      "QB": {
        "status": "locked",
        "starter": "Kyler Murray",
        "epa_per_dropback": 0.115,
        "dropbacks": 571
      },
      "RB": {
        "status": "contested",
        "starter": "James Conner",
        "carries_per_game": 14.8,
        "carry_share": 0.636,
        "carries": 236
      },
      "WR": {
        "status": "locked",
        "starter": "Marvin Harrison",
        "target_share": 0.222,
        "targets": 116
      },
      "TE": {
        "status": "locked",
        "starter": "Trey McBride",
        "target_share": 0.281,
        "targets": 147
      }
    },
    "ATL": {
      "QB": {
        "status": "contested",
        "starter": "Kirk Cousins",
        "epa_per_dropback": 0.044,
        "dropbacks": 481
      },
      "RB": {
        "status": "locked",
        "starter": "Bijan Robinson",
        "carries_per_game": 17.9,
        "carry_share": 0.67,
        "carries": 304
      },
      "WR": {
        "status": "locked",
        "starter": "Drake London",
        "target_share": 0.293,
        "targets": 158
      },
      "TE": {
        "status": "contested",
        "starter": "Kyle Pitts",
        "target_share": 0.137,
        "targets": 74
      }
    },
    "BAL": {
      "QB": {
        "status": "locked",
        "starter": "Lamar Jackson",
        "epa_per_dropback": 0.347,
        "dropbacks": 497
      },
      "RB": {
        "status": "locked",
        "starter": "Derrick Henry",
        "carries_per_game": 19.1,
        "carry_share": 0.819,
        "carries": 325
      },
      "WR": {
        "status": "locked",
        "starter": "Zay Flowers",
        "target_share": 0.254,
        "targets": 116
      },
      "TE": {
        "status": "contested",
        "starter": "Mark Andrews",
        "target_share": 0.151,
        "targets": 69
      }
    },
    "BUF": {
      "QB": {
        "status": "locked",
        "starter": "Josh Allen",
        "epa_per_dropback": 0.262,
        "dropbacks": 497
      },
      "RB": {
        "status": "contested",
        "starter": "James Cook",
        "carries_per_game": 12.9,
        "carry_share": 0.569,
        "carries": 207
      },
      "WR": {
        "status": "contested",
        "starter": "Khalil Shakir",
        "target_share": 0.202,
        "targets": 100
      },
      "TE": {
        "status": "contested",
        "starter": "Dalton Kincaid",
        "target_share": 0.152,
        "targets": 75
      }
    },
    "CAR": {
      "QB": {
        "status": "contested",
        "starter": "Bryce Young",
        "epa_per_dropback": -0.063,
        "dropbacks": 413
      },
      "RB": {
        "status": "locked",
        "starter": "Chuba Hubbard",
        "carries_per_game": 16.7,
        "carry_share": 0.725,
        "carries": 250
      },
      "WR": {
        "status": "contested",
        "starter": "Xavier Legette",
        "target_share": 0.162,
        "targets": 84
      },
      "TE": {
        "status": "contested",
        "starter": "Ja'Tavion Sanders",
        "target_share": 0.083,
        "targets": 43
      }
    },
    "CHI": {
      "QB": {
        "status": "contested",
        "starter": "Caleb Williams",
        "epa_per_dropback": -0.075,
        "dropbacks": 630
      },
      "RB": {
        "status": "locked",
        "starter": "D'Andre Swift",
        "carries_per_game": 14.9,
        "carry_share": 0.798,
        "carries": 253
      },
      "WR": {
        "status": "locked",
        "starter": "D.J. Moore",
        "target_share": 0.266,
        "targets": 140
      },
      "TE": {
        "status": "contested",
        "starter": "Cole Kmet",
        "target_share": 0.105,
        "targets": 55
      }
    },
    "CIN": {
      "QB": {
        "status": "locked",
        "starter": "Joe Burrow",
        "epa_per_dropback": 0.164,
        "dropbacks": 700
      },
      "RB": {
        "status": "locked",
        "starter": "Chase Brown",
        "carries_per_game": 14.3,
        "carry_share": 0.676,
        "carries": 229
      },
      "WR": {
        "status": "locked",
        "starter": "Ja'Marr Chase",
        "target_share": 0.279,
        "targets": 175
      },
      "TE": {
        "status": "contested",
        "starter": "Mike Gesicki",
        "target_share": 0.132,
        "targets": 83
      }
    },
    "CLE": {
      "QB": {
        "status": "contested",
        "starter": "Jameis Winston",
        "epa_per_dropback": -0.08,
        "dropbacks": 320
      },
      "RB": {
        "status": "contested",
        "starter": "Jerome Ford",
        "carries_per_game": 7.4,
        "carry_share": 0.338,
        "carries": 104
      },
      "WR": {
        "status": "locked",
        "starter": "Jerry Jeudy",
        "target_share": 0.229,
        "targets": 145
      },
      "TE": {
        "status": "locked",
        "starter": "David Njoku",
        "target_share": 0.153,
        "targets": 97
      }
    },
    "DAL": {
      "QB": {
        "status": "contested",
        "starter": "Cooper Rush",
        "epa_per_dropback": -0.071,
        "dropbacks": 321
      },
      "RB": {
        "status": "locked",
        "starter": "Rico Dowdle",
        "carries_per_game": 14.7,
        "carry_share": 0.679,
        "carries": 235
      },
      "WR": {
        "status": "locked",
        "starter": "CeeDee Lamb",
        "target_share": 0.244,
        "targets": 152
      },
      "TE": {
        "status": "contested",
        "starter": "Jake Ferguson",
        "target_share": 0.138,
        "targets": 86
      }
    },
    "DEN": {
      "QB": {
        "status": "locked",
        "starter": "Bo Nix",
        "epa_per_dropback": 0.058,
        "dropbacks": 591
      },
      "RB": {
        "status": "contested",
        "starter": "Javonte Williams",
        "carries_per_game": 8.2,
        "carry_share": 0.397,
        "carries": 139
      },
      "WR": {
        "status": "locked",
        "starter": "Courtland Sutton",
        "target_share": 0.246,
        "targets": 135
      },
      "TE": {
        "status": "open",
        "starter": "Lucas Krull",
        "target_share": 0.042,
        "targets": 23
      }
    },
    "DET": {
      "QB": {
        "status": "locked",
        "starter": "Jared Goff",
        "epa_per_dropback": 0.296,
        "dropbacks": 570
      },
      "RB": {
        "status": "contested",
        "starter": "Jahmyr Gibbs",
        "carries_per_game": 14.7,
        "carry_share": 0.523,
        "carries": 250
      },
      "WR": {
        "status": "locked",
        "starter": "Amon-Ra St. Brown",
        "target_share": 0.27,
        "targets": 141
      },
      "TE": {
        "status": "locked",
        "starter": "Sam LaPorta",
        "target_share": 0.159,
        "targets": 83
      }
    },
    "GB": {
      "QB": {
        "status": "locked",
        "starter": "Jordan Love",
        "epa_per_dropback": 0.142,
        "dropbacks": 439
      },
      "RB": {
        "status": "locked",
        "starter": "Josh Jacobs",
        "carries_per_game": 17.7,
        "carry_share": 0.675,
        "carries": 301
      },
      "WR": {
        "status": "contested",
        "starter": "Dontayvion Wicks",
        "target_share": 0.164,
        "targets": 76
      },
      "TE": {
        "status": "contested",
        "starter": "Tucker Kraft",
        "target_share": 0.151,
        "targets": 70
      }
    },
    "HOU": {
      "QB": {
        "status": "contested",
        "starter": "C.J. Stroud",
        "epa_per_dropback": -0.022,
        "dropbacks": 584
      },
      "RB": {
        "status": "locked",
        "starter": "Joe Mixon",
        "carries_per_game": 17.5,
        "carry_share": 0.752,
        "carries": 245
      },
      "WR": {
        "status": "contested",
        "starter": "Nico Collins",
        "target_share": 0.181,
        "targets": 99
      },
      "TE": {
        "status": "locked",
        "starter": "Dalton Schultz",
        "target_share": 0.155,
        "targets": 85
      }
    },
    "IND": {
      "QB": {
        "status": "contested",
        "starter": "Anthony Richardson",
        "epa_per_dropback": -0.141,
        "dropbacks": 278
      },
      "RB": {
        "status": "locked",
        "starter": "Jonathan Taylor",
        "carries_per_game": 21.6,
        "carry_share": 0.775,
        "carries": 303
      },
      "WR": {
        "status": "locked",
        "starter": "Michael Pittman",
        "target_share": 0.226,
        "targets": 111
      },
      "TE": {
        "status": "open",
        "starter": "Kylen Granson",
        "target_share": 0.063,
        "targets": 31
      }
    },
    "JAX": {
      "QB": {
        "status": "contested",
        "starter": "Trevor Lawrence",
        "epa_per_dropback": 0.02,
        "dropbacks": 302
      },
      "RB": {
        "status": "contested",
        "starter": "Tank Bigsby",
        "carries_per_game": 10.5,
        "carry_share": 0.48,
        "carries": 168
      },
      "WR": {
        "status": "locked",
        "starter": "Brian Thomas",
        "target_share": 0.255,
        "targets": 133
      },
      "TE": {
        "status": "contested",
        "starter": "Evan Engram",
        "target_share": 0.123,
        "targets": 64
      }
    },
    "KC": {
      "QB": {
        "status": "locked",
        "starter": "Patrick Mahomes",
        "epa_per_dropback": 0.115,
        "dropbacks": 617
      },
      "RB": {
        "status": "contested",
        "starter": "Kareem Hunt",
        "carries_per_game": 15.4,
        "carry_share": 0.557,
        "carries": 200
      },
      "WR": {
        "status": "contested",
        "starter": "Xavier Worthy",
        "target_share": 0.171,
        "targets": 98
      },
      "TE": {
        "status": "locked",
        "starter": "Travis Kelce",
        "target_share": 0.233,
        "targets": 133
      }
    },
    "LAC": {
      "QB": {
        "status": "locked",
        "starter": "Justin Herbert",
        "epa_per_dropback": 0.132,
        "dropbacks": 545
      },
      "RB": {
        "status": "contested",
        "starter": "J.K. Dobbins",
        "carries_per_game": 15,
        "carry_share": 0.523,
        "carries": 195
      },
      "WR": {
        "status": "locked",
        "starter": "Ladd McConkey",
        "target_share": 0.228,
        "targets": 112
      },
      "TE": {
        "status": "contested",
        "starter": "Will Dissly",
        "target_share": 0.13,
        "targets": 64
      }
    },
    "LAR": {
      "QB": {
        "status": "locked",
        "starter": "Matthew Stafford",
        "epa_per_dropback": 0.06,
        "dropbacks": 545
      },
      "RB": {
        "status": "locked",
        "starter": "Kyren Williams",
        "carries_per_game": 19.8,
        "carry_share": 0.796,
        "carries": 316
      },
      "WR": {
        "status": "contested",
        "starter": "Puka Nacua",
        "target_share": 0.196,
        "targets": 106
      },
      "TE": {
        "status": "contested",
        "starter": "Colby Parkinson",
        "target_share": 0.091,
        "targets": 49
      }
    },
    "LVR": {
      "QB": {
        "status": "contested",
        "starter": "Gardner Minshew",
        "epa_per_dropback": -0.137,
        "dropbacks": 335
      },
      "RB": {
        "status": "contested",
        "starter": "Alexander Mattison",
        "carries_per_game": 9.4,
        "carry_share": 0.426,
        "carries": 132
      },
      "WR": {
        "status": "contested",
        "starter": "Jakobi Meyers",
        "target_share": 0.218,
        "targets": 129
      },
      "TE": {
        "status": "locked",
        "starter": "Brock Bowers",
        "target_share": 0.258,
        "targets": 153
      }
    },
    "MIA": {
      "QB": {
        "status": "locked",
        "starter": "Tua Tagovailoa",
        "epa_per_dropback": 0.204,
        "dropbacks": 420
      },
      "RB": {
        "status": "contested",
        "starter": "Devon Achane",
        "carries_per_game": 11.9,
        "carry_share": 0.531,
        "carries": 203
      },
      "WR": {
        "status": "contested",
        "starter": "Tyreek Hill",
        "target_share": 0.215,
        "targets": 122
      },
      "TE": {
        "status": "locked",
        "starter": "Jonnu Smith",
        "target_share": 0.195,
        "targets": 111
      }
    },
    "MIN": {
      "QB": {
        "status": "locked",
        "starter": "Sam Darnold",
        "epa_per_dropback": 0.084,
        "dropbacks": 593
      },
      "RB": {
        "status": "contested",
        "starter": "Aaron Jones",
        "carries_per_game": 15,
        "carry_share": 0.607,
        "carries": 255
      },
      "WR": {
        "status": "locked",
        "starter": "Justin Jefferson",
        "target_share": 0.298,
        "targets": 154
      },
      "TE": {
        "status": "contested",
        "starter": "T.J. Hockenson",
        "target_share": 0.12,
        "targets": 62
      }
    },
    "NE": {
      "QB": {
        "status": "contested",
        "starter": "Drake Maye",
        "epa_per_dropback": -0.071,
        "dropbacks": 372
      },
      "RB": {
        "status": "contested",
        "starter": "Rhamondre Stevenson",
        "carries_per_game": 13.8,
        "carry_share": 0.575,
        "carries": 207
      },
      "WR": {
        "status": "contested",
        "starter": "Demario Douglas",
        "target_share": 0.174,
        "targets": 87
      },
      "TE": {
        "status": "locked",
        "starter": "Hunter Henry",
        "target_share": 0.194,
        "targets": 97
      }
    },
    "NOR": {
      "QB": {
        "status": "contested",
        "starter": "Derek Carr",
        "epa_per_dropback": 0.166,
        "dropbacks": 287
      },
      "RB": {
        "status": "locked",
        "starter": "Alvin Kamara",
        "carries_per_game": 16.3,
        "carry_share": 0.655,
        "carries": 228
      },
      "WR": {
        "status": "open",
        "starter": "Marquez Valdes-Scantling",
        "target_share": 0.089,
        "targets": 44
      },
      "TE": {
        "status": "contested",
        "starter": "Juwan Johnson",
        "target_share": 0.128,
        "targets": 66
      }
    },
    "NYG": {
      "QB": {
        "status": "contested",
        "starter": "Daniel Jones",
        "epa_per_dropback": -0.103,
        "dropbacks": 370
      },
      "RB": {
        "status": "contested",
        "starter": "Tyrone Tracy",
        "carries_per_game": 11.3,
        "carry_share": 0.602,
        "carries": 192
      },
      "WR": {
        "status": "locked",
        "starter": "Malik Nabers",
        "target_share": 0.307,
        "targets": 170
      },
      "TE": {
        "status": "contested",
        "starter": "Theo Johnson",
        "target_share": 0.078,
        "targets": 43
      }
    },
    "NYJ": {
      "QB": {
        "status": "contested",
        "starter": "Aaron Rodgers",
        "epa_per_dropback": 0.018,
        "dropbacks": 624
      },
      "RB": {
        "status": "contested",
        "starter": "Breece Hall",
        "carries_per_game": 13.1,
        "carry_share": 0.631,
        "carries": 209
      },
      "WR": {
        "status": "locked",
        "starter": "Garrett Wilson",
        "target_share": 0.26,
        "targets": 153
      },
      "TE": {
        "status": "contested",
        "starter": "Tyler Conklin",
        "target_share": 0.122,
        "targets": 72
      }
    },
    "PHI": {
      "QB": {
        "status": "locked",
        "starter": "Jalen Hurts",
        "epa_per_dropback": 0.101,
        "dropbacks": 399
      },
      "RB": {
        "status": "locked",
        "starter": "Saquon Barkley",
        "carries_per_game": 21.6,
        "carry_share": 0.762,
        "carries": 345
      },
      "WR": {
        "status": "locked",
        "starter": "A.J. Brown",
        "target_share": 0.232,
        "targets": 97
      },
      "TE": {
        "status": "contested",
        "starter": "Dallas Goedert",
        "target_share": 0.124,
        "targets": 52
      }
    },
    "PIT": {
      "QB": {
        "status": "contested",
        "starter": "Russell Wilson",
        "epa_per_dropback": -0.005,
        "dropbacks": 369
      },
      "RB": {
        "status": "contested",
        "starter": "Najee Harris",
        "carries_per_game": 15.5,
        "carry_share": 0.617,
        "carries": 263
      },
      "WR": {
        "status": "locked",
        "starter": "George Pickens",
        "target_share": 0.224,
        "targets": 103
      },
      "TE": {
        "status": "contested",
        "starter": "Pat Freiermuth",
        "target_share": 0.17,
        "targets": 78
      }
    },
    "SEA": {
      "QB": {
        "status": "contested",
        "starter": "Geno Smith",
        "epa_per_dropback": 0.035,
        "dropbacks": 628
      },
      "RB": {
        "status": "contested",
        "starter": "Kenneth Walker",
        "carries_per_game": 13.9,
        "carry_share": 0.475,
        "carries": 153
      },
      "WR": {
        "status": "locked",
        "starter": "Jaxon Smith-Njigba",
        "target_share": 0.241,
        "targets": 137
      },
      "TE": {
        "status": "contested",
        "starter": "Noah Fant",
        "target_share": 0.112,
        "targets": 64
      }
    },
    "SF": {
      "QB": {
        "status": "locked",
        "starter": "Brock Purdy",
        "epa_per_dropback": 0.16,
        "dropbacks": 486
      },
      "RB": {
        "status": "contested",
        "starter": "Jordan Mason",
        "carries_per_game": 12.8,
        "carry_share": 0.459,
        "carries": 153
      },
      "WR": {
        "status": "locked",
        "starter": "Jauan Jennings",
        "target_share": 0.22,
        "targets": 113
      },
      "TE": {
        "status": "locked",
        "starter": "George Kittle",
        "target_share": 0.183,
        "targets": 94
      }
    },
    "TB": {
      "QB": {
        "status": "locked",
        "starter": "Baker Mayfield",
        "epa_per_dropback": 0.189,
        "dropbacks": 610
      },
      "RB": {
        "status": "contested",
        "starter": "Bucky Irving",
        "carries_per_game": 12.2,
        "carry_share": 0.516,
        "carries": 207
      },
      "WR": {
        "status": "contested",
        "starter": "Mike Evans",
        "target_share": 0.195,
        "targets": 110
      },
      "TE": {
        "status": "locked",
        "starter": "Cade Otton",
        "target_share": 0.155,
        "targets": 87
      }
    },
    "TEN": {
      "QB": {
        "status": "contested",
        "starter": "Will Levis",
        "epa_per_dropback": -0.192,
        "dropbacks": 342
      },
      "RB": {
        "status": "locked",
        "starter": "Tony Pollard",
        "carries_per_game": 16.3,
        "carry_share": 0.708,
        "carries": 260
      },
      "WR": {
        "status": "locked",
        "starter": "Calvin Ridley",
        "target_share": 0.237,
        "targets": 120
      },
      "TE": {
        "status": "contested",
        "starter": "Chigoziem Okonkwo",
        "target_share": 0.138,
        "targets": 70
      }
    },
    "WAS": {
      "QB": {
        "status": "locked",
        "starter": "Jayden Daniels",
        "epa_per_dropback": 0.115,
        "dropbacks": 527
      },
      "RB": {
        "status": "contested",
        "starter": "Brian Robinson",
        "carries_per_game": 13.4,
        "carry_share": 0.528,
        "carries": 187
      },
      "WR": {
        "status": "locked",
        "starter": "Terry McLaurin",
        "target_share": 0.232,
        "targets": 117
      },
      "TE": {
        "status": "locked",
        "starter": "Zach Ertz",
        "target_share": 0.181,
        "targets": 91
      }
    }
  },
  "picks": [
    {
      "key": "1.01-Fernando Mendoza-LVR",
      "pick": "1.01",
      "round": 1,
      "overall": 1,
      "name": "Fernando Mendoza",
      "school": "Indiana",
      "team": "LVR",
      "pos": "QB",
      "roomStatus": "contested",
      "starter": "Gardner Minshew",
      "draftCapital": 1,
      "roomFactor": 0.6,
      "score": 0.6,
      "grade": "B",
      "rationale": "Contested room (vs Gardner Minshew) — competing for snaps."
    },
    {
      "key": "1.13-Ty Simpson-LAR",
      "pick": "1.13",
      "round": 1,
      "overall": 13,
      "name": "Ty Simpson",
      "school": "Alabama",
      "team": "LAR",
      "pos": "QB",
      "roomStatus": "locked",
      "starter": "Matthew Stafford",
      "draftCapital": 1,
      "roomFactor": 0.2,
      "score": 0.2,
      "grade": "D",
      "rationale": "Locked behind Matthew Stafford — limited Year-1 path."
    },
    {
      "key": "3.65-Carson Beck-ARI",
      "pick": "3.65",
      "round": 3,
      "overall": 65,
      "name": "Carson Beck",
      "school": "Miami",
      "team": "ARI",
      "pos": "QB",
      "roomStatus": "locked",
      "starter": "Kyler Murray",
      "draftCapital": 0.55,
      "roomFactor": 0.2,
      "score": 0.11,
      "grade": "D",
      "rationale": "Locked behind Kyler Murray — limited Year-1 path."
    },
    {
      "key": "3.76-Drew Allar-PIT",
      "pick": "3.76",
      "round": 3,
      "overall": 76,
      "name": "Drew Allar",
      "school": "Penn State",
      "team": "PIT",
      "pos": "QB",
      "roomStatus": "contested",
      "starter": "Russell Wilson",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Russell Wilson) — competing for snaps."
    },
    {
      "key": "4.110-Cade Klubnick-NYJ",
      "pick": "4.110",
      "round": 4,
      "overall": 110,
      "name": "Cade Klubnick",
      "school": "Clemson",
      "team": "NYJ",
      "pos": "QB",
      "roomStatus": "contested",
      "starter": "Aaron Rodgers",
      "draftCapital": 0.35,
      "roomFactor": 0.6,
      "score": 0.21,
      "grade": "D",
      "rationale": "Contested room (vs Aaron Rodgers) — competing for snaps."
    },
    {
      "key": "5.178-Cole Payton-PHI",
      "pick": "5.178",
      "round": 5,
      "overall": 178,
      "name": "Cole Payton",
      "school": "North Dakota State",
      "team": "PHI",
      "pos": "QB",
      "roomStatus": "locked",
      "starter": "Jalen Hurts",
      "draftCapital": 0.2,
      "roomFactor": 0.2,
      "score": 0.04,
      "grade": "D",
      "rationale": "Locked behind Jalen Hurts — limited Year-1 path."
    },
    {
      "key": "6.182-Taylen Green-CLE",
      "pick": "6.182",
      "round": 6,
      "overall": 182,
      "name": "Taylen Green",
      "school": "Arkansas",
      "team": "CLE",
      "pos": "QB",
      "roomStatus": "contested",
      "starter": "Jameis Winston",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Jameis Winston) — competing for snaps."
    },
    {
      "key": "7.223-Athan Kaliakmanis-WAS",
      "pick": "7.223",
      "round": 7,
      "overall": 223,
      "name": "Athan Kaliakmanis",
      "school": "Rutgers",
      "team": "WAS",
      "pos": "QB",
      "roomStatus": "locked",
      "starter": "Jayden Daniels",
      "draftCapital": 0.1,
      "roomFactor": 0.2,
      "score": 0.02,
      "grade": "D",
      "rationale": "Locked behind Jayden Daniels — limited Year-1 path."
    },
    {
      "key": "7.234-Behren Morton-NE",
      "pick": "7.234",
      "round": 7,
      "overall": 234,
      "name": "Behren Morton",
      "school": "Texas Tech",
      "team": "NE",
      "pos": "QB",
      "roomStatus": "contested",
      "starter": "Drake Maye",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Drake Maye) — competing for snaps."
    },
    {
      "key": "7.249-Garrett Nussmeier-KC",
      "pick": "7.249",
      "round": 7,
      "overall": 249,
      "name": "Garrett Nussmeier",
      "school": "LSU",
      "team": "KC",
      "pos": "QB",
      "roomStatus": "locked",
      "starter": "Patrick Mahomes",
      "draftCapital": 0.1,
      "roomFactor": 0.2,
      "score": 0.02,
      "grade": "D",
      "rationale": "Locked behind Patrick Mahomes — limited Year-1 path."
    },
    {
      "key": "1.03-Jeremiyah Love-ARI",
      "pick": "1.03",
      "round": 1,
      "overall": 3,
      "name": "Jeremiyah Love",
      "school": "Notre Dame",
      "team": "ARI",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "James Conner",
      "draftCapital": 1,
      "roomFactor": 0.6,
      "score": 0.6,
      "grade": "B",
      "rationale": "Contested room (vs James Conner) — competing for snaps."
    },
    {
      "key": "1.32-Jadarian Price-SEA",
      "pick": "1.32",
      "round": 1,
      "overall": 32,
      "name": "Jadarian Price",
      "school": "Notre Dame",
      "team": "SEA",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Kenneth Walker",
      "draftCapital": 1,
      "roomFactor": 0.6,
      "score": 0.6,
      "grade": "B",
      "rationale": "Contested room (vs Kenneth Walker) — competing for snaps."
    },
    {
      "key": "3.90-Kaelon Black-SF",
      "pick": "3.90",
      "round": 3,
      "overall": 90,
      "name": "Kaelon Black",
      "school": "Vanderbilt",
      "team": "SF",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Jordan Mason",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Jordan Mason) — competing for snaps."
    },
    {
      "key": "4.108-Jonah Coleman-DEN",
      "pick": "4.108",
      "round": 4,
      "overall": 108,
      "name": "Jonah Coleman",
      "school": "Washington",
      "team": "DEN",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Javonte Williams",
      "draftCapital": 0.35,
      "roomFactor": 0.6,
      "score": 0.21,
      "grade": "D",
      "rationale": "Contested room (vs Javonte Williams) — competing for snaps."
    },
    {
      "key": "4.122-Mike Washington-LVR",
      "pick": "4.122",
      "round": 4,
      "overall": 122,
      "name": "Mike Washington",
      "school": "Florida State",
      "team": "LVR",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Alexander Mattison",
      "draftCapital": 0.35,
      "roomFactor": 0.6,
      "score": 0.21,
      "grade": "D",
      "rationale": "Contested room (vs Alexander Mattison) — competing for snaps."
    },
    {
      "key": "5.161-Emmett Johnson-KC",
      "pick": "5.161",
      "round": 5,
      "overall": 161,
      "name": "Emmett Johnson",
      "school": "Nebraska",
      "team": "KC",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Kareem Hunt",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Kareem Hunt) — competing for snaps."
    },
    {
      "key": "5.165-Nicholas Singleton-TEN",
      "pick": "5.165",
      "round": 5,
      "overall": 165,
      "name": "Nicholas Singleton",
      "school": "Penn State",
      "team": "TEN",
      "pos": "RB",
      "roomStatus": "locked",
      "starter": "Tony Pollard",
      "draftCapital": 0.2,
      "roomFactor": 0.2,
      "score": 0.04,
      "grade": "D",
      "rationale": "Locked behind Tony Pollard — limited Year-1 path."
    },
    {
      "key": "5.174-Adam Randall-BAL",
      "pick": "5.174",
      "round": 5,
      "overall": 174,
      "name": "Adam Randall",
      "school": "Clemson",
      "team": "BAL",
      "pos": "RB",
      "roomStatus": "locked",
      "starter": "Derrick Henry",
      "draftCapital": 0.2,
      "roomFactor": 0.2,
      "score": 0.04,
      "grade": "D",
      "rationale": "Locked behind Derrick Henry — limited Year-1 path."
    },
    {
      "key": "6.187-Kaytron Allen-WAS",
      "pick": "6.187",
      "round": 6,
      "overall": 187,
      "name": "Kaytron Allen",
      "school": "Penn State",
      "team": "WAS",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Brian Robinson",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Brian Robinson) — competing for snaps."
    },
    {
      "key": "6.198-Demond Claiborne-MIN",
      "pick": "6.198",
      "round": 6,
      "overall": 198,
      "name": "Demond Claiborne",
      "school": "Wake Forest",
      "team": "MIN",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Aaron Jones",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Aaron Jones) — competing for snaps."
    },
    {
      "key": "7.230-Eli Heidenreich-PIT",
      "pick": "7.230",
      "round": 7,
      "overall": 230,
      "name": "Eli Heidenreich",
      "school": "Navy",
      "team": "PIT",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Najee Harris",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Najee Harris) — competing for snaps."
    },
    {
      "key": "7.237-Seth McGowan-SEA",
      "pick": "7.237",
      "round": 7,
      "overall": 237,
      "name": "Seth McGowan",
      "school": "Oregon",
      "team": "SEA",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Kenneth Walker",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Kenneth Walker) — competing for snaps."
    },
    {
      "key": "7.245-Jam Miller-NE",
      "pick": "7.245",
      "round": 7,
      "overall": 245,
      "name": "Jam Miller",
      "school": "Alabama",
      "team": "NE",
      "pos": "RB",
      "roomStatus": "contested",
      "starter": "Rhamondre Stevenson",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Rhamondre Stevenson) — competing for snaps."
    },
    {
      "key": "1.04-Carnell Tate-TEN",
      "pick": "1.04",
      "round": 1,
      "overall": 4,
      "name": "Carnell Tate",
      "school": "Ohio State",
      "team": "TEN",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Calvin Ridley",
      "draftCapital": 1,
      "roomFactor": 0.45,
      "score": 0.45,
      "grade": "C",
      "rationale": "Locked behind Calvin Ridley — limited Year-1 path."
    },
    {
      "key": "1.08-Jordyn Tyson-NOR",
      "pick": "1.08",
      "round": 1,
      "overall": 8,
      "name": "Jordyn Tyson",
      "school": "Arizona State",
      "team": "NOR",
      "pos": "WR",
      "roomStatus": "open",
      "starter": "Marquez Valdes-Scantling",
      "draftCapital": 1,
      "roomFactor": 1,
      "score": 1,
      "grade": "A+",
      "rationale": "Open room — clearest path to immediate touches."
    },
    {
      "key": "1.20-Makai Lemon-PHI",
      "pick": "1.20",
      "round": 1,
      "overall": 20,
      "name": "Makai Lemon",
      "school": "USC",
      "team": "PHI",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "A.J. Brown",
      "draftCapital": 1,
      "roomFactor": 0.45,
      "score": 0.45,
      "grade": "C",
      "rationale": "Locked behind A.J. Brown — limited Year-1 path."
    },
    {
      "key": "1.24-KC Concepcion-CLE",
      "pick": "1.24",
      "round": 1,
      "overall": 24,
      "name": "KC Concepcion",
      "school": "Texas A&M",
      "team": "CLE",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Jerry Jeudy",
      "draftCapital": 1,
      "roomFactor": 0.45,
      "score": 0.45,
      "grade": "C",
      "rationale": "Locked behind Jerry Jeudy — limited Year-1 path."
    },
    {
      "key": "1.30-Omar Cooper Jr.-NYJ",
      "pick": "1.30",
      "round": 1,
      "overall": 30,
      "name": "Omar Cooper Jr.",
      "school": "Indiana",
      "team": "NYJ",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Garrett Wilson",
      "draftCapital": 1,
      "roomFactor": 0.45,
      "score": 0.45,
      "grade": "C",
      "rationale": "Locked behind Garrett Wilson — limited Year-1 path."
    },
    {
      "key": "2.33-De'Zhaun Stribling-SF",
      "pick": "2.33",
      "round": 2,
      "overall": 33,
      "name": "De'Zhaun Stribling",
      "school": "Oregon State",
      "team": "SF",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Jauan Jennings",
      "draftCapital": 0.75,
      "roomFactor": 0.45,
      "score": 0.338,
      "grade": "D",
      "rationale": "Locked behind Jauan Jennings — limited Year-1 path."
    },
    {
      "key": "2.39-Denzel Boston-CLE",
      "pick": "2.39",
      "round": 2,
      "overall": 39,
      "name": "Denzel Boston",
      "school": "Washington",
      "team": "CLE",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Jerry Jeudy",
      "draftCapital": 0.75,
      "roomFactor": 0.45,
      "score": 0.338,
      "grade": "D",
      "rationale": "Locked behind Jerry Jeudy — limited Year-1 path."
    },
    {
      "key": "2.47-Germie Bernard-PIT",
      "pick": "2.47",
      "round": 2,
      "overall": 47,
      "name": "Germie Bernard",
      "school": "Alabama",
      "team": "PIT",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "George Pickens",
      "draftCapital": 0.75,
      "roomFactor": 0.45,
      "score": 0.338,
      "grade": "D",
      "rationale": "Locked behind George Pickens — limited Year-1 path."
    },
    {
      "key": "3.71-Antonio Williams-WAS",
      "pick": "3.71",
      "round": 3,
      "overall": 71,
      "name": "Antonio Williams",
      "school": "Clemson",
      "team": "WAS",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Terry McLaurin",
      "draftCapital": 0.55,
      "roomFactor": 0.45,
      "score": 0.248,
      "grade": "D",
      "rationale": "Locked behind Terry McLaurin — limited Year-1 path."
    },
    {
      "key": "3.74-Malachi Fields-NYG",
      "pick": "3.74",
      "round": 3,
      "overall": 74,
      "name": "Malachi Fields",
      "school": "Notre Dame",
      "team": "NYG",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Malik Nabers",
      "draftCapital": 0.55,
      "roomFactor": 0.45,
      "score": 0.248,
      "grade": "D",
      "rationale": "Locked behind Malik Nabers — limited Year-1 path."
    },
    {
      "key": "3.75-Caleb Douglas-MIA",
      "pick": "3.75",
      "round": 3,
      "overall": 75,
      "name": "Caleb Douglas",
      "school": "Florida",
      "team": "MIA",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Tyreek Hill",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Tyreek Hill) — competing for snaps."
    },
    {
      "key": "3.79-Zacharia Branch-ATL",
      "pick": "3.79",
      "round": 3,
      "overall": 79,
      "name": "Zacharia Branch",
      "school": "Georgia",
      "team": "ATL",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Drake London",
      "draftCapital": 0.55,
      "roomFactor": 0.45,
      "score": 0.248,
      "grade": "D",
      "rationale": "Locked behind Drake London — limited Year-1 path."
    },
    {
      "key": "3.80-Ja'Kobi Lane-BAL",
      "pick": "3.80",
      "round": 3,
      "overall": 80,
      "name": "Ja'Kobi Lane",
      "school": "USC",
      "team": "BAL",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Zay Flowers",
      "draftCapital": 0.55,
      "roomFactor": 0.45,
      "score": 0.248,
      "grade": "D",
      "rationale": "Locked behind Zay Flowers — limited Year-1 path."
    },
    {
      "key": "3.83-Chris Brazzell Jr-CAR",
      "pick": "3.83",
      "round": 3,
      "overall": 83,
      "name": "Chris Brazzell Jr",
      "school": "Tennessee",
      "team": "CAR",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Xavier Legette",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Xavier Legette) — competing for snaps."
    },
    {
      "key": "3.84-Ted Hurst-TB",
      "pick": "3.84",
      "round": 3,
      "overall": 84,
      "name": "Ted Hurst",
      "school": "Arkansas",
      "team": "TB",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Mike Evans",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Mike Evans) — competing for snaps."
    },
    {
      "key": "3.89-Zavion Thomas-CHI",
      "pick": "3.89",
      "round": 3,
      "overall": 89,
      "name": "Zavion Thomas",
      "school": "LSU",
      "team": "CHI",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "D.J. Moore",
      "draftCapital": 0.55,
      "roomFactor": 0.45,
      "score": 0.248,
      "grade": "D",
      "rationale": "Locked behind D.J. Moore — limited Year-1 path."
    },
    {
      "key": "3.94-Chris Bell-MIA",
      "pick": "3.94",
      "round": 3,
      "overall": 94,
      "name": "Chris Bell",
      "school": "Louisville",
      "team": "MIA",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Tyreek Hill",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Tyreek Hill) — competing for snaps."
    },
    {
      "key": "4.105-Brenen Thompson-LAC",
      "pick": "4.105",
      "round": 4,
      "overall": 105,
      "name": "Brenen Thompson",
      "school": "Texas",
      "team": "LAC",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Ladd McConkey",
      "draftCapital": 0.35,
      "roomFactor": 0.45,
      "score": 0.158,
      "grade": "D",
      "rationale": "Locked behind Ladd McConkey — limited Year-1 path."
    },
    {
      "key": "4.115-Elijah Sarratt-BAL",
      "pick": "4.115",
      "round": 4,
      "overall": 115,
      "name": "Elijah Sarratt",
      "school": "Indiana",
      "team": "BAL",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Zay Flowers",
      "draftCapital": 0.35,
      "roomFactor": 0.45,
      "score": 0.158,
      "grade": "D",
      "rationale": "Locked behind Zay Flowers — limited Year-1 path."
    },
    {
      "key": "4.121-Kaden Wetjen-PIT",
      "pick": "4.121",
      "round": 4,
      "overall": 121,
      "name": "Kaden Wetjen",
      "school": "Iowa",
      "team": "PIT",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "George Pickens",
      "draftCapital": 0.35,
      "roomFactor": 0.45,
      "score": 0.158,
      "grade": "D",
      "rationale": "Locked behind George Pickens — limited Year-1 path."
    },
    {
      "key": "4.125-Skyler Bell-BUF",
      "pick": "4.125",
      "round": 4,
      "overall": 125,
      "name": "Skyler Bell",
      "school": "Wisconsin",
      "team": "BUF",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Khalil Shakir",
      "draftCapital": 0.35,
      "roomFactor": 0.6,
      "score": 0.21,
      "grade": "D",
      "rationale": "Contested room (vs Khalil Shakir) — competing for snaps."
    },
    {
      "key": "4.136-Bryce Lance-NOR",
      "pick": "4.136",
      "round": 4,
      "overall": 136,
      "name": "Bryce Lance",
      "school": "North Dakota State",
      "team": "NOR",
      "pos": "WR",
      "roomStatus": "open",
      "starter": "Marquez Valdes-Scantling",
      "draftCapital": 0.35,
      "roomFactor": 1,
      "score": 0.35,
      "grade": "D",
      "rationale": "Open room — clearest path to immediate touches."
    },
    {
      "key": "4.140-Colbie Young-CIN",
      "pick": "4.140",
      "round": 4,
      "overall": 140,
      "name": "Colbie Young",
      "school": "Georgia",
      "team": "CIN",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Ja'Marr Chase",
      "draftCapital": 0.35,
      "roomFactor": 0.45,
      "score": 0.158,
      "grade": "D",
      "rationale": "Locked behind Ja'Marr Chase — limited Year-1 path."
    },
    {
      "key": "5.143-Reggie Virgil-ARI",
      "pick": "5.143",
      "round": 5,
      "overall": 143,
      "name": "Reggie Virgil",
      "school": "Miami (OH)",
      "team": "ARI",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Marvin Harrison",
      "draftCapital": 0.2,
      "roomFactor": 0.45,
      "score": 0.09,
      "grade": "D",
      "rationale": "Locked behind Marvin Harrison — limited Year-1 path."
    },
    {
      "key": "5.168-Kendrick Law-DET",
      "pick": "5.168",
      "round": 5,
      "overall": 168,
      "name": "Kendrick Law",
      "school": "Alabama",
      "team": "DET",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Amon-Ra St. Brown",
      "draftCapital": 0.2,
      "roomFactor": 0.45,
      "score": 0.09,
      "grade": "D",
      "rationale": "Locked behind Amon-Ra St. Brown — limited Year-1 path."
    },
    {
      "key": "5.176-Cyrus Allen-KC",
      "pick": "5.176",
      "round": 5,
      "overall": 176,
      "name": "Cyrus Allen",
      "school": "Texas Tech",
      "team": "KC",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Xavier Worthy",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Xavier Worthy) — competing for snaps."
    },
    {
      "key": "5.177-Kevin Coleman Jr.-MIA",
      "pick": "5.177",
      "round": 5,
      "overall": 177,
      "name": "Kevin Coleman Jr.",
      "school": "Mississippi State",
      "team": "MIA",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Tyreek Hill",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Tyreek Hill) — competing for snaps."
    },
    {
      "key": "6.190-Barion Brown-NOR",
      "pick": "6.190",
      "round": 6,
      "overall": 190,
      "name": "Barion Brown",
      "school": "LSU",
      "team": "NOR",
      "pos": "WR",
      "roomStatus": "open",
      "starter": "Marquez Valdes-Scantling",
      "draftCapital": 0.1,
      "roomFactor": 1,
      "score": 0.1,
      "grade": "D",
      "rationale": "Open room — clearest path to immediate touches."
    },
    {
      "key": "6.191-Josh Cameron-JAX",
      "pick": "6.191",
      "round": 6,
      "overall": 191,
      "name": "Josh Cameron",
      "school": "Baylor",
      "team": "JAX",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Brian Thomas",
      "draftCapital": 0.1,
      "roomFactor": 0.45,
      "score": 0.045,
      "grade": "D",
      "rationale": "Locked behind Brian Thomas — limited Year-1 path."
    },
    {
      "key": "6.195-Malik Benson-LVR",
      "pick": "6.195",
      "round": 6,
      "overall": 195,
      "name": "Malik Benson",
      "school": "Florida State",
      "team": "LVR",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Jakobi Meyers",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Jakobi Meyers) — competing for snaps."
    },
    {
      "key": "6.197-CJ Daniels-LAR",
      "pick": "6.197",
      "round": 6,
      "overall": 197,
      "name": "CJ Daniels",
      "school": "Maryland",
      "team": "LAR",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Puka Nacua",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Puka Nacua) — competing for snaps."
    },
    {
      "key": "6.199-Emmanuel Henderson Jr.-SEA",
      "pick": "6.199",
      "round": 6,
      "overall": 199,
      "name": "Emmanuel Henderson Jr.",
      "school": "Alabama",
      "team": "SEA",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Jaxon Smith-Njigba",
      "draftCapital": 0.1,
      "roomFactor": 0.45,
      "score": 0.045,
      "grade": "D",
      "rationale": "Locked behind Jaxon Smith-Njigba — limited Year-1 path."
    },
    {
      "key": "6.203-C.J. Williams-JAX",
      "pick": "6.203",
      "round": 6,
      "overall": 203,
      "name": "C.J. Williams",
      "school": "Wisconsin",
      "team": "JAX",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Brian Thomas",
      "draftCapital": 0.1,
      "roomFactor": 0.45,
      "score": 0.045,
      "grade": "D",
      "rationale": "Locked behind Brian Thomas — limited Year-1 path."
    },
    {
      "key": "6.204-Lewis Bond-HOU",
      "pick": "6.204",
      "round": 6,
      "overall": 204,
      "name": "Lewis Bond",
      "school": "Boston College",
      "team": "HOU",
      "pos": "WR",
      "roomStatus": "contested",
      "starter": "Nico Collins",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Nico Collins) — competing for snaps."
    },
    {
      "key": "7.218-Anthony Smith-DAL",
      "pick": "7.218",
      "round": 7,
      "overall": 218,
      "name": "Anthony Smith",
      "school": "Tulane",
      "team": "DAL",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "CeeDee Lamb",
      "draftCapital": 0.1,
      "roomFactor": 0.45,
      "score": 0.045,
      "grade": "D",
      "rationale": "Locked behind CeeDee Lamb — limited Year-1 path."
    },
    {
      "key": "7.254-Deion Burks-IND",
      "pick": "7.254",
      "round": 7,
      "overall": 254,
      "name": "Deion Burks",
      "school": "Oklahoma",
      "team": "IND",
      "pos": "WR",
      "roomStatus": "locked",
      "starter": "Michael Pittman",
      "draftCapital": 0.1,
      "roomFactor": 0.45,
      "score": 0.045,
      "grade": "D",
      "rationale": "Locked behind Michael Pittman — limited Year-1 path."
    },
    {
      "key": "1.16-Kenyon Sadiq-NYJ",
      "pick": "1.16",
      "round": 1,
      "overall": 16,
      "name": "Kenyon Sadiq",
      "school": "Oregon",
      "team": "NYJ",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Tyler Conklin",
      "draftCapital": 1,
      "roomFactor": 0.6,
      "score": 0.6,
      "grade": "B",
      "rationale": "Contested room (vs Tyler Conklin) — competing for snaps."
    },
    {
      "key": "2.54-Eli Stowers-PHI",
      "pick": "2.54",
      "round": 2,
      "overall": 54,
      "name": "Eli Stowers",
      "school": "Vanderbilt",
      "team": "PHI",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Dallas Goedert",
      "draftCapital": 0.75,
      "roomFactor": 0.6,
      "score": 0.45,
      "grade": "C",
      "rationale": "Contested room (vs Dallas Goedert) — competing for snaps."
    },
    {
      "key": "2.56-Nate Boerkircher-JAX",
      "pick": "2.56",
      "round": 2,
      "overall": 56,
      "name": "Nate Boerkircher",
      "school": "Nebraska",
      "team": "JAX",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Evan Engram",
      "draftCapital": 0.75,
      "roomFactor": 0.6,
      "score": 0.45,
      "grade": "C",
      "rationale": "Contested room (vs Evan Engram) — competing for snaps."
    },
    {
      "key": "2.59-Marlin Klein-HOU",
      "pick": "2.59",
      "round": 2,
      "overall": 59,
      "name": "Marlin Klein",
      "school": "Michigan",
      "team": "HOU",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "Dalton Schultz",
      "draftCapital": 0.75,
      "roomFactor": 0.2,
      "score": 0.15,
      "grade": "D",
      "rationale": "Locked behind Dalton Schultz — limited Year-1 path."
    },
    {
      "key": "2.61-Max Klare-LAR",
      "pick": "2.61",
      "round": 2,
      "overall": 61,
      "name": "Max Klare",
      "school": "Ohio State",
      "team": "LAR",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Colby Parkinson",
      "draftCapital": 0.75,
      "roomFactor": 0.6,
      "score": 0.45,
      "grade": "C",
      "rationale": "Contested room (vs Colby Parkinson) — competing for snaps."
    },
    {
      "key": "3.69-Sam Roush-CHI",
      "pick": "3.69",
      "round": 3,
      "overall": 69,
      "name": "Sam Roush",
      "school": "Northwestern",
      "team": "CHI",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Cole Kmet",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Cole Kmet) — competing for snaps."
    },
    {
      "key": "3.73-Oscar Delp-NOR",
      "pick": "3.73",
      "round": 3,
      "overall": 73,
      "name": "Oscar Delp",
      "school": "Georgia",
      "team": "NOR",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Juwan Johnson",
      "draftCapital": 0.55,
      "roomFactor": 0.6,
      "score": 0.33,
      "grade": "D",
      "rationale": "Contested room (vs Juwan Johnson) — competing for snaps."
    },
    {
      "key": "3.87-Will Kacmarek-MIA",
      "pick": "3.87",
      "round": 3,
      "overall": 87,
      "name": "Will Kacmarek",
      "school": "Ohio",
      "team": "MIA",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "Jonnu Smith",
      "draftCapital": 0.55,
      "roomFactor": 0.2,
      "score": 0.11,
      "grade": "D",
      "rationale": "Locked behind Jonnu Smith — limited Year-1 path."
    },
    {
      "key": "3.95-Eli Raridon-NEP",
      "pick": "3.95",
      "round": 3,
      "overall": 95,
      "name": "Eli Raridon",
      "school": "Notre Dame",
      "team": "NEP",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "Hunter Henry",
      "draftCapital": 0.55,
      "roomFactor": 0.2,
      "score": 0.11,
      "grade": "D",
      "rationale": "Locked behind Hunter Henry — limited Year-1 path."
    },
    {
      "key": "4.133-Matthew Hibner-BAL",
      "pick": "4.133",
      "round": 4,
      "overall": 133,
      "name": "Matthew Hibner",
      "school": "Virginia",
      "team": "BAL",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Mark Andrews",
      "draftCapital": 0.35,
      "roomFactor": 0.6,
      "score": 0.21,
      "grade": "D",
      "rationale": "Contested room (vs Mark Andrews) — competing for snaps."
    },
    {
      "key": "5.152-Justin Joly-DEN",
      "pick": "5.152",
      "round": 5,
      "overall": 152,
      "name": "Justin Joly",
      "school": "NC State",
      "team": "DEN",
      "pos": "TE",
      "roomStatus": "open",
      "starter": "Lucas Krull",
      "draftCapital": 0.2,
      "roomFactor": 1,
      "score": 0.2,
      "grade": "D",
      "rationale": "Open room — clearest path to immediate touches."
    },
    {
      "key": "5.159-Max Bredeson-MIN",
      "pick": "5.159",
      "round": 5,
      "overall": 159,
      "name": "Max Bredeson",
      "school": "Wisconsin",
      "team": "MIN",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "T.J. Hockenson",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs T.J. Hockenson) — competing for snaps."
    },
    {
      "key": "5.164-Tanner Koziol-JAX",
      "pick": "5.164",
      "round": 5,
      "overall": 164,
      "name": "Tanner Koziol",
      "school": "Houston",
      "team": "JAX",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Evan Engram",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Evan Engram) — competing for snaps."
    },
    {
      "key": "5.169-Riley Nowakowski-PIT",
      "pick": "5.169",
      "round": 5,
      "overall": 169,
      "name": "Riley Nowakowski",
      "school": "Wisconsin",
      "team": "PIT",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Pat Freiermuth",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Pat Freiermuth) — competing for snaps."
    },
    {
      "key": "5.170-Joe Royer-CLE",
      "pick": "5.170",
      "round": 5,
      "overall": 170,
      "name": "Joe Royer",
      "school": "Cincinnati",
      "team": "CLE",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "David Njoku",
      "draftCapital": 0.2,
      "roomFactor": 0.2,
      "score": 0.04,
      "grade": "D",
      "rationale": "Locked behind David Njoku — limited Year-1 path."
    },
    {
      "key": "5.173-Josh Cuevas-BAL",
      "pick": "5.173",
      "round": 5,
      "overall": 173,
      "name": "Josh Cuevas",
      "school": "Cal Poly",
      "team": "BAL",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Mark Andrews",
      "draftCapital": 0.2,
      "roomFactor": 0.6,
      "score": 0.12,
      "grade": "D",
      "rationale": "Contested room (vs Mark Andrews) — competing for snaps."
    },
    {
      "key": "5.180-Seydou Traore-MIA",
      "pick": "5.180",
      "round": 5,
      "overall": 180,
      "name": "Seydou Traore",
      "school": "Arkansas",
      "team": "MIA",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "Jonnu Smith",
      "draftCapital": 0.2,
      "roomFactor": 0.2,
      "score": 0.04,
      "grade": "D",
      "rationale": "Locked behind Jonnu Smith — limited Year-1 path."
    },
    {
      "key": "6.185-Bauer Sharp-TB",
      "pick": "6.185",
      "round": 6,
      "overall": 185,
      "name": "Bauer Sharp",
      "school": "Oklahoma",
      "team": "TB",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "Cade Otton",
      "draftCapital": 0.1,
      "roomFactor": 0.2,
      "score": 0.02,
      "grade": "D",
      "rationale": "Locked behind Cade Otton — limited Year-1 path."
    },
    {
      "key": "7.221-Jack Endries-CIN",
      "pick": "7.221",
      "round": 7,
      "overall": 221,
      "name": "Jack Endries",
      "school": "Texas",
      "team": "CIN",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Mike Gesicki",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Mike Gesicki) — competing for snaps."
    },
    {
      "key": "7.225-Jaren Kanak-TEN",
      "pick": "7.225",
      "round": 7,
      "overall": 225,
      "name": "Jaren Kanak",
      "school": "Oklahoma",
      "team": "TEN",
      "pos": "TE",
      "roomStatus": "contested",
      "starter": "Chigoziem Okonkwo",
      "draftCapital": 0.1,
      "roomFactor": 0.6,
      "score": 0.06,
      "grade": "D",
      "rationale": "Contested room (vs Chigoziem Okonkwo) — competing for snaps."
    },
    {
      "key": "7.248-Carsen Ryan-CLE",
      "pick": "7.248",
      "round": 7,
      "overall": 248,
      "name": "Carsen Ryan",
      "school": "Utah",
      "team": "CLE",
      "pos": "TE",
      "roomStatus": "locked",
      "starter": "David Njoku",
      "draftCapital": 0.1,
      "roomFactor": 0.2,
      "score": 0.02,
      "grade": "D",
      "rationale": "Locked behind David Njoku — limited Year-1 path."
    },
    {
      "key": "7.256-Dallen Bentley-DEN",
      "pick": "7.256",
      "round": 7,
      "overall": 256,
      "name": "Dallen Bentley",
      "school": "BYU",
      "team": "DEN",
      "pos": "TE",
      "roomStatus": "open",
      "starter": "Lucas Krull",
      "draftCapital": 0.1,
      "roomFactor": 1,
      "score": 0.1,
      "grade": "D",
      "rationale": "Open room — clearest path to immediate touches."
    }
  ]
};
