// Analysis view — pairs each rookie pick with the drafting team's incumbent
// depth chart at that position, so you can see who they'd be competing with.
// Data comes from analysis.js (generated by scripts/build-analysis.mjs).

const STATUS_LABEL = { open: 'Open', contested: 'Contested', locked: 'Locked' };
const STATUS_COLOR = {
  open:      { bg: 'oklch(92% 0.06 145)', fg: 'oklch(35% 0.12 145)' },
  contested: { bg: 'oklch(92% 0.07 70)',  fg: 'oklch(35% 0.12 55)'  },
  locked:    { bg: 'oklch(92% 0.05 25)',  fg: 'oklch(40% 0.13 25)'  },
};
const STATUS_COLOR_DARK = {
  open:      { bg: 'oklch(28% 0.07 145)', fg: 'oklch(82% 0.10 145)' },
  contested: { bg: 'oklch(28% 0.07 60)',  fg: 'oklch(82% 0.10 65)'  },
  locked:    { bg: 'oklch(28% 0.07 25)',  fg: 'oklch(82% 0.10 25)'  },
};

const ANALYSIS_POSITIONS = ['QB', 'RB', 'WR', 'TE'];

const AnalysisView = ({ search, palette, dark, hoverPick, setHoverPick }) => {
  const data = window.ANALYSIS_DATA;
  const teams = window.DRAFT_DATA.teams;
  const [posFilter, setPosFilter] = React.useState('all');

  if (!data) {
    return (
      <div className="analysis-empty">
        <div className="team-empty-icon">—</div>
        <div className="team-empty-text">Analysis data not loaded.</div>
        <div className="team-empty-sub">run scripts/build-analysis.mjs</div>
      </div>
    );
  }

  const q = (search || '').trim().toLowerCase();
  const rows = data.picks
    .filter(p => !q || p.name.toLowerCase().includes(q))
    .filter(p => posFilter === 'all' || p.pos === posFilter)
    .sort((a, b) => a.overall - b.overall);

  const statusColor = (status) =>
    (dark ? STATUS_COLOR_DARK : STATUS_COLOR)[status] || STATUS_COLOR.open;

  return (
    <div className="analysis-view">
      <div className="analysis-meta">
        <div>
          <span className="analysis-meta-label">Source</span>
          <span className="analysis-meta-value">{data.source}</span>
        </div>
        <div>
          <span className="analysis-meta-label">Season</span>
          <span className="analysis-meta-value">{data.season}</span>
        </div>
        <div>
          <span className="analysis-meta-label">Generated</span>
          <span className="analysis-meta-value">{data.generatedAt}</span>
        </div>
      </div>

      <div className="analysis-filters">
        <div className="analysis-pos-filter">
          <button
            type="button"
            className={`pos-chip${posFilter === 'all' ? ' is-active' : ''}`}
            onClick={() => setPosFilter('all')}
          >All</button>
          {ANALYSIS_POSITIONS.map(p => (
            <button
              key={p}
              type="button"
              data-pos={p}
              className={`pos-chip${posFilter === p ? ' is-active' : ''}`}
              onClick={() => setPosFilter(posFilter === p ? 'all' : p)}
            >{p}</button>
          ))}
        </div>
        <div className="analysis-count">
          {rows.length} / {data.picks.length} picks
        </div>
      </div>

      <div className="analysis-list">
        {rows.length === 0 && (
          <div className="empty-row">No picks match your filters.</div>
        )}
        {rows.map(p => {
          const teamCode = p.team === 'NEP' ? 'NE' : p.team;
          const team = teams[teamCode];
          const room = data.rooms[teamCode]?.[p.pos] || { status: 'open', incumbents: [] };
          const swatch = window.roundSwatch(palette, p.round, dark);
          const sc = statusColor(room.status);
          const isHover = hoverPick === p.key;
          const incumbents = room.incumbents || [];
          return (
            <div
              key={p.key}
              className={`dc-row${isHover ? ' is-hover' : ''}`}
              onMouseEnter={() => setHoverPick(p.key)}
              onMouseLeave={() => setHoverPick(null)}
            >
              <div className="dc-rookie">
                <div className="dc-pick" style={{ background: swatch.bg, color: swatch.fg }}>
                  <span className="rd">RD {p.round}</span>
                  <span className="ov">{p.overall}</span>
                </div>
                <div className="dc-pos" data-pos={p.pos}>{p.pos}</div>
                <div className="dc-rookie-info">
                  <div className="dc-rookie-name">{p.name}</div>
                  {p.school && <div className="dc-rookie-school">{p.school}</div>}
                </div>
              </div>

              <div className="dc-arrow" aria-hidden="true">→</div>

              <div className="dc-room">
                <div className="dc-room-header">
                  <TeamBadge code={p.team} size={28} />
                  <div className="dc-room-title">
                    <span className="dc-room-team">{team?.short}</span>
                    <span className="dc-room-pos">{p.pos} room</span>
                  </div>
                  <span
                    className="dc-status"
                    style={{ background: sc.bg, color: sc.fg }}
                  >{STATUS_LABEL[room.status]}</span>
                </div>
                {incumbents.length > 0 ? (
                  <ol className="dc-incumbents">
                    {incumbents.map((inc, i) => (
                      <li key={inc.name} className="dc-incumbent">
                        <span className="dc-incumbent-rank">{i + 1}</span>
                        <span className="dc-incumbent-name">{inc.name}</span>
                        <span className="dc-incumbent-stat">
                          <span className="dc-stat-value">{inc.primary_value}</span>
                          <span className="dc-stat-label">{inc.primary_label}</span>
                        </span>
                        <span className="dc-incumbent-stat secondary">
                          <span className="dc-stat-value">{inc.secondary_value}</span>
                          <span className="dc-stat-label">{inc.secondary_label}</span>
                        </span>
                      </li>
                    ))}
                  </ol>
                ) : (
                  <div className="dc-empty">No incumbents with meaningful {data.season} production.</div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="analysis-legend">
        <div className="analysis-legend-title">About this view</div>
        <div className="analysis-legend-body">
          Each rookie is paired with the drafting team's depth chart at their position from the
          {' '}{data.season} regular season. <strong>Open</strong> = nobody locked in;{' '}
          <strong>Contested</strong> = real competition for snaps;{' '}
          <strong>Locked</strong> = entrenched starter. Stats from nflverse: EPA/dropback for QBs,
          carries/game + share for RBs, target share for WR/TE.
        </div>
      </div>
    </div>
  );
};

window.AnalysisView = AnalysisView;
