// NFL Draft picks - Fantasy relevant (QB/RB/WR/TE)
// pick format: "round.overall"
window.DRAFT_DATA = {
  picks: [
    // Quarterbacks
    { pick: "1.01", round: 1, overall: 1, name: "Fernando Mendoza", team: "LVR", pos: "QB", school: "Indiana" },
    { pick: "1.13", round: 1, overall: 13, name: "Ty Simpson", team: "LAR", pos: "QB", school: "Alabama" },
    { pick: "3.65", round: 3, overall: 65, name: "Carson Beck", team: "ARI", pos: "QB", school: "Miami" },
    { pick: "3.76", round: 3, overall: 76, name: "Drew Allar", team: "PIT", pos: "QB", school: "Penn State" },
    { pick: "4.110", round: 4, overall: 110, name: "Cade Klubnick", team: "NYJ", pos: "QB", school: "Clemson" },
    { pick: "5.178", round: 5, overall: 178, name: "Cole Payton", team: "PHI", pos: "QB", school: "North Dakota State" },
    { pick: "6.182", round: 6, overall: 182, name: "Taylen Green", team: "CLE", pos: "QB", school: "Arkansas" },
    { pick: "7.223", round: 7, overall: 223, name: "Athan Kaliakmanis", team: "WAS", pos: "QB", school: "Rutgers" },
    { pick: "7.234", round: 7, overall: 234, name: "Behren Morton", team: "NE", pos: "QB", school: "Texas Tech" },
    { pick: "7.249", round: 7, overall: 249, name: "Garrett Nussmeier", team: "KC", pos: "QB", school: "LSU" },

    // Running Backs
    { pick: "1.03", round: 1, overall: 3, name: "Jeremiyah Love", team: "ARI", pos: "RB", school: "Notre Dame" },
    { pick: "1.32", round: 1, overall: 32, name: "Jadarian Price", team: "SEA", pos: "RB", school: "Notre Dame" },
    { pick: "3.90", round: 3, overall: 90, name: "Kaelon Black", team: "SF", pos: "RB", school: "Vanderbilt" },
    { pick: "4.108", round: 4, overall: 108, name: "Jonah Coleman", team: "DEN", pos: "RB", school: "Washington" },
    { pick: "4.122", round: 4, overall: 122, name: "Mike Washington", team: "LVR", pos: "RB", school: "Florida State" },
    { pick: "5.161", round: 5, overall: 161, name: "Emmett Johnson", team: "KC", pos: "RB", school: "Nebraska" },
    { pick: "5.165", round: 5, overall: 165, name: "Nicholas Singleton", team: "TEN", pos: "RB", school: "Penn State" },
    { pick: "5.174", round: 5, overall: 174, name: "Adam Randall", team: "BAL", pos: "RB", school: "Clemson" },
    { pick: "6.187", round: 6, overall: 187, name: "Kaytron Allen", team: "WAS", pos: "RB", school: "Penn State" },
    { pick: "6.198", round: 6, overall: 198, name: "Demond Claiborne", team: "MIN", pos: "RB", school: "Wake Forest" },
    { pick: "7.230", round: 7, overall: 230, name: "Eli Heidenreich", team: "PIT", pos: "RB", school: "Navy" },
    { pick: "7.237", round: 7, overall: 237, name: "Seth McGowan", team: "SEA", pos: "RB", school: "Oregon" },
    { pick: "7.245", round: 7, overall: 245, name: "Jam Miller", team: "NE", pos: "RB", school: "Alabama" },

    // Wide Receivers
    { pick: "1.04", round: 1, overall: 4, name: "Carnell Tate", team: "TEN", pos: "WR", school: "Ohio State" },
    { pick: "1.08", round: 1, overall: 8, name: "Jordyn Tyson", team: "NOR", pos: "WR", school: "Arizona State" },
    { pick: "1.20", round: 1, overall: 20, name: "Makai Lemon", team: "PHI", pos: "WR", school: "USC" },
    { pick: "1.24", round: 1, overall: 24, name: "KC Concepcion", team: "CLE", pos: "WR", school: "Texas A&M" },
    { pick: "1.30", round: 1, overall: 30, name: "Omar Cooper Jr.", team: "NYJ", pos: "WR", school: "Indiana" },
    { pick: "2.33", round: 2, overall: 33, name: "De'Zhaun Stribling", team: "SF", pos: "WR", school: "Oregon State" },
    { pick: "2.39", round: 2, overall: 39, name: "Denzel Boston", team: "CLE", pos: "WR", school: "Washington" },
    { pick: "2.47", round: 2, overall: 47, name: "Germie Bernard", team: "PIT", pos: "WR", school: "Alabama" },
    { pick: "3.71", round: 3, overall: 71, name: "Antonio Williams", team: "WAS", pos: "WR", school: "Clemson" },
    { pick: "3.74", round: 3, overall: 74, name: "Malachi Fields", team: "NYG", pos: "WR", school: "Notre Dame" },
    { pick: "3.75", round: 3, overall: 75, name: "Caleb Douglas", team: "MIA", pos: "WR", school: "Florida" },
    { pick: "3.79", round: 3, overall: 79, name: "Zacharia Branch", team: "ATL", pos: "WR", school: "Georgia" },
    { pick: "3.80", round: 3, overall: 80, name: "Ja'Kobi Lane", team: "BAL", pos: "WR", school: "USC" },
    { pick: "3.83", round: 3, overall: 83, name: "Chris Brazzell Jr", team: "CAR", pos: "WR", school: "Tennessee" },
    { pick: "3.84", round: 3, overall: 84, name: "Ted Hurst", team: "TB", pos: "WR", school: "Arkansas" },
    { pick: "3.89", round: 3, overall: 89, name: "Zavion Thomas", team: "CHI", pos: "WR", school: "LSU" },
    { pick: "3.94", round: 3, overall: 94, name: "Chris Bell", team: "MIA", pos: "WR", school: "Louisville" },
    { pick: "4.105", round: 4, overall: 105, name: "Brenen Thompson", team: "LAC", pos: "WR", school: "Texas" },
    { pick: "4.115", round: 4, overall: 115, name: "Elijah Sarratt", team: "BAL", pos: "WR", school: "Indiana" },
    { pick: "4.121", round: 4, overall: 121, name: "Kaden Wetjen", team: "PIT", pos: "WR", school: "Iowa" },
    { pick: "4.125", round: 4, overall: 125, name: "Skyler Bell", team: "BUF", pos: "WR", school: "Wisconsin" },
    { pick: "4.136", round: 4, overall: 136, name: "Bryce Lance", team: "NOR", pos: "WR", school: "North Dakota State" },
    { pick: "4.140", round: 4, overall: 140, name: "Colbie Young", team: "CIN", pos: "WR", school: "Georgia" },
    { pick: "5.143", round: 5, overall: 143, name: "Reggie Virgil", team: "ARI", pos: "WR", school: "Miami (OH)" },
    { pick: "5.168", round: 5, overall: 168, name: "Kendrick Law", team: "DET", pos: "WR", school: "Alabama" },
    { pick: "5.176", round: 5, overall: 176, name: "Cyrus Allen", team: "KC", pos: "WR", school: "Texas Tech" },
    { pick: "5.177", round: 5, overall: 177, name: "Kevin Coleman Jr.", team: "MIA", pos: "WR", school: "Mississippi State" },
    { pick: "6.190", round: 6, overall: 190, name: "Barion Brown", team: "NOR", pos: "WR", school: "LSU" },
    { pick: "6.191", round: 6, overall: 191, name: "Josh Cameron", team: "JAX", pos: "WR", school: "Baylor" },
    { pick: "6.195", round: 6, overall: 195, name: "Malik Benson", team: "LVR", pos: "WR", school: "Florida State" },
    { pick: "6.197", round: 6, overall: 197, name: "CJ Daniels", team: "LAR", pos: "WR", school: "Maryland" },
    { pick: "6.199", round: 6, overall: 199, name: "Emmanuel Henderson Jr.", team: "SEA", pos: "WR", school: "Alabama" },
    { pick: "6.203", round: 6, overall: 203, name: "C.J. Williams", team: "JAX", pos: "WR", school: "Wisconsin" },
    { pick: "6.204", round: 6, overall: 204, name: "Lewis Bond", team: "HOU", pos: "WR", school: "Boston College" },
    { pick: "7.218", round: 7, overall: 218, name: "Anthony Smith", team: "DAL", pos: "WR", school: "Tulane" },
    { pick: "7.254", round: 7, overall: 254, name: "Deion Burks", team: "IND", pos: "WR", school: "Oklahoma" },

    // Tight Ends
    { pick: "1.16", round: 1, overall: 16, name: "Kenyon Sadiq", team: "NYJ", pos: "TE", school: "Oregon" },
    { pick: "2.54", round: 2, overall: 54, name: "Eli Stowers", team: "PHI", pos: "TE", school: "Vanderbilt" },
    { pick: "2.56", round: 2, overall: 56, name: "Nate Boerkircher", team: "JAX", pos: "TE", school: "Nebraska" },
    { pick: "2.59", round: 2, overall: 59, name: "Marlin Klein", team: "HOU", pos: "TE", school: "Michigan" },
    { pick: "2.61", round: 2, overall: 61, name: "Max Klare", team: "LAR", pos: "TE", school: "Ohio State" },
    { pick: "3.69", round: 3, overall: 69, name: "Sam Roush", team: "CHI", pos: "TE", school: "Northwestern" },
    { pick: "3.73", round: 3, overall: 73, name: "Oscar Delp", team: "NOR", pos: "TE", school: "Georgia" },
    { pick: "3.87", round: 3, overall: 87, name: "Will Kacmarek", team: "MIA", pos: "TE", school: "Ohio" },
    { pick: "3.95", round: 3, overall: 95, name: "Eli Raridon", team: "NEP", pos: "TE", school: "Notre Dame" },
    { pick: "4.133", round: 4, overall: 133, name: "Matthew Hibner", team: "BAL", pos: "TE", school: "Virginia" },
    { pick: "5.152", round: 5, overall: 152, name: "Justin Joly", team: "DEN", pos: "TE", school: "NC State" },
    { pick: "5.159", round: 5, overall: 159, name: "Max Bredeson", team: "MIN", pos: "TE", school: "Wisconsin" },
    { pick: "5.164", round: 5, overall: 164, name: "Tanner Koziol", team: "JAX", pos: "TE", school: "Houston" },
    { pick: "5.169", round: 5, overall: 169, name: "Riley Nowakowski", team: "PIT", pos: "TE", school: "Wisconsin" },
    { pick: "5.170", round: 5, overall: 170, name: "Joe Royer", team: "CLE", pos: "TE", school: "Cincinnati" },
    { pick: "5.173", round: 5, overall: 173, name: "Josh Cuevas", team: "BAL", pos: "TE", school: "Cal Poly" },
    { pick: "5.180", round: 5, overall: 180, name: "Seydou Traore", team: "MIA", pos: "TE", school: "Arkansas" },
    { pick: "6.185", round: 6, overall: 185, name: "Bauer Sharp", team: "TB", pos: "TE", school: "Oklahoma" },
    { pick: "7.221", round: 7, overall: 221, name: "Jack Endries", team: "CIN", pos: "TE", school: "Texas" },
    { pick: "7.225", round: 7, overall: 225, name: "Jaren Kanak", team: "TEN", pos: "TE", school: "Oklahoma" },
    { pick: "7.248", round: 7, overall: 248, name: "Carsen Ryan", team: "CLE", pos: "TE", school: "Utah" },
    { pick: "7.256", round: 7, overall: 256, name: "Dallen Bentley", team: "DEN", pos: "TE", school: "BYU" },
  ],

  // 32 NFL teams with brand colors (primary, secondary), full names, and ESPN logo slugs.
  // espn slug feeds https://a.espncdn.com/i/teamlogos/nfl/500/{espn}.png
  teams: {
    ARI: { name: "Arizona Cardinals",   city: "Arizona",     short: "Cardinals",  primary: "#97233F", secondary: "#000000", text: "#FFFFFF", espn: "ari" },
    ATL: { name: "Atlanta Falcons",     city: "Atlanta",     short: "Falcons",    primary: "#A71930", secondary: "#000000", text: "#FFFFFF", espn: "atl" },
    BAL: { name: "Baltimore Ravens",    city: "Baltimore",   short: "Ravens",     primary: "#241773", secondary: "#9E7C0C", text: "#FFFFFF", espn: "bal" },
    BUF: { name: "Buffalo Bills",       city: "Buffalo",     short: "Bills",      primary: "#00338D", secondary: "#C60C30", text: "#FFFFFF", espn: "buf" },
    CAR: { name: "Carolina Panthers",   city: "Carolina",    short: "Panthers",   primary: "#0085CA", secondary: "#101820", text: "#FFFFFF", espn: "car" },
    CHI: { name: "Chicago Bears",       city: "Chicago",     short: "Bears",      primary: "#0B162A", secondary: "#C83803", text: "#FFFFFF", espn: "chi" },
    CIN: { name: "Cincinnati Bengals",  city: "Cincinnati",  short: "Bengals",    primary: "#FB4F14", secondary: "#000000", text: "#000000", espn: "cin" },
    CLE: { name: "Cleveland Browns",    city: "Cleveland",   short: "Browns",     primary: "#311D00", secondary: "#FF3C00", text: "#FFFFFF", espn: "cle" },
    DAL: { name: "Dallas Cowboys",      city: "Dallas",      short: "Cowboys",    primary: "#003594", secondary: "#869397", text: "#FFFFFF", espn: "dal" },
    DEN: { name: "Denver Broncos",      city: "Denver",      short: "Broncos",    primary: "#FB4F14", secondary: "#002244", text: "#002244", espn: "den" },
    DET: { name: "Detroit Lions",       city: "Detroit",     short: "Lions",      primary: "#0076B6", secondary: "#B0B7BC", text: "#FFFFFF", espn: "det" },
    GB:  { name: "Green Bay Packers",   city: "Green Bay",   short: "Packers",    primary: "#203731", secondary: "#FFB612", text: "#FFB612", espn: "gb"  },
    HOU: { name: "Houston Texans",      city: "Houston",     short: "Texans",     primary: "#03202F", secondary: "#A71930", text: "#FFFFFF", espn: "hou" },
    IND: { name: "Indianapolis Colts",  city: "Indianapolis",short: "Colts",      primary: "#002C5F", secondary: "#A2AAAD", text: "#FFFFFF", espn: "ind" },
    JAX: { name: "Jacksonville Jaguars",city: "Jacksonville",short: "Jaguars",    primary: "#101820", secondary: "#D7A22A", text: "#D7A22A", espn: "jax" },
    KC:  { name: "Kansas City Chiefs",  city: "Kansas City", short: "Chiefs",     primary: "#E31837", secondary: "#FFB81C", text: "#FFFFFF", espn: "kc"  },
    LAC: { name: "Los Angeles Chargers",city: "LA",          short: "Chargers",   primary: "#0080C6", secondary: "#FFC20E", text: "#FFFFFF", espn: "lac" },
    LAR: { name: "Los Angeles Rams",    city: "LA",          short: "Rams",       primary: "#003594", secondary: "#FFA300", text: "#FFA300", espn: "lar" },
    LVR: { name: "Las Vegas Raiders",   city: "Las Vegas",   short: "Raiders",    primary: "#000000", secondary: "#A5ACAF", text: "#A5ACAF", espn: "lv"  },
    MIA: { name: "Miami Dolphins",      city: "Miami",       short: "Dolphins",   primary: "#008E97", secondary: "#FC4C02", text: "#FFFFFF", espn: "mia" },
    MIN: { name: "Minnesota Vikings",   city: "Minnesota",   short: "Vikings",    primary: "#4F2683", secondary: "#FFC62F", text: "#FFC62F", espn: "min" },
    NE:  { name: "New England Patriots",city: "New England", short: "Patriots",   primary: "#002244", secondary: "#C60C30", text: "#FFFFFF", espn: "ne"  },
    NEP: { name: "New England Patriots",city: "New England", short: "Patriots",   primary: "#002244", secondary: "#C60C30", text: "#FFFFFF", espn: "ne"  },
    NOR: { name: "New Orleans Saints",  city: "New Orleans", short: "Saints",     primary: "#101820", secondary: "#D3BC8D", text: "#D3BC8D", espn: "no"  },
    NYG: { name: "New York Giants",     city: "NY Giants",   short: "Giants",     primary: "#0B2265", secondary: "#A71930", text: "#FFFFFF", espn: "nyg" },
    NYJ: { name: "New York Jets",       city: "NY Jets",     short: "Jets",       primary: "#125740", secondary: "#000000", text: "#FFFFFF", espn: "nyj" },
    PHI: { name: "Philadelphia Eagles", city: "Philadelphia",short: "Eagles",     primary: "#004C54", secondary: "#A5ACAF", text: "#FFFFFF", espn: "phi" },
    PIT: { name: "Pittsburgh Steelers", city: "Pittsburgh",  short: "Steelers",   primary: "#101820", secondary: "#FFB612", text: "#FFB612", espn: "pit" },
    SEA: { name: "Seattle Seahawks",    city: "Seattle",     short: "Seahawks",   primary: "#002244", secondary: "#69BE28", text: "#69BE28", espn: "sea" },
    SF:  { name: "San Francisco 49ers", city: "SF",          short: "49ers",      primary: "#AA0000", secondary: "#B3995D", text: "#B3995D", espn: "sf"  },
    TB:  { name: "Tampa Bay Buccaneers",city: "Tampa Bay",   short: "Buccaneers", primary: "#D50A0A", secondary: "#0A0A08", text: "#FFFFFF", espn: "tb"  },
    TEN: { name: "Tennessee Titans",    city: "Tennessee",   short: "Titans",     primary: "#0C2340", secondary: "#4B92DB", text: "#4B92DB", espn: "ten" },
    WAS: { name: "Washington Commanders",city:"Washington",  short: "Commanders", primary: "#5A1414", secondary: "#FFB612", text: "#FFB612", espn: "wsh" },
  }
};
